### ISSUE TITLE
TransactSQL astify not creating valid ast for OVER PARTITION

### ISSUE THREAD

**Issue by MarkSak** [taozhi8833998/node-sql-parser#1052]
Given the following T-SQL Statement as input

`const SQL = 'SELECT syscolumns.name, ROW_NUMBER() OVER(PARTITION BY id ORDER BY colid) rowNo from sysColumns';
`

When parsed into ast with the Default option:

`const ast = parser.astify(SQL);`

ast:
```
{
    "columns": [
        {
            "as": null,
            "expr": {
                "column": "name",
                "table": "syscolumns",
                "type": "column_ref"
            }
        },
        {
            "as": "rowNo",
            "expr": {
                "args": {
                    "type": "expr_list",
                    "value": [
                    ]
                },
                "name": "ROW_NUMBER",
                "over": {
                    "as_window_specification": {
                        "parentheses": true,
                        "window_specification": {
                            "name": null,
                            "orderby": [
                                {
                                    "expr": {
                                        "column": "colid",
                                        "table": null,
                                        "type": "column_ref"
                                    },
                                    "type": "ASC"
                                }
                            ],
                            "partitionby": [
                                {
                                    "as": null,
                                    "expr": {
                                        "column": "id",
                                        "table": null,
                                        "type": "column_ref"
                                    }
                                }
                            ],
                            "window_frame_clause": null
                        }
                    },
                    "type": "window"
                },
                "type": "function"
            }
        }
    ],
    "distinct": null,
    "for_update": null,
    "from": [
        {
            "as": null,
            "db": null,
            "table": "sysColumns"
        }
    ],
    "groupby": null,
    "having": null,
    "into": {
        "position": null
    },
    "limit": null,
    "options": null,
    "orderby": null,
    "type": "select",
    "where": null,
    "window": null,
    "with": null
}
```

Converted back to T-SQL:
`const sql = parser.sqlify(ast, {database: 'TransactSQL'});`

sql:
`SELECT [syscolumns].[name], ROW_NUMBER() OVER (PARTITION BY [id] ORDER BY [colid] ASC) AS [rowNo] FROM [sysColumns]`

However, when the SQL is parsed into ast with TransactSQL option, the produced ast is missing the "as_window_specification" object and attempting to parse it back into SQL fails, 

`const ast = parser.astify(SQL, {database: 'TransactSQL'});`

ast:
```
{
    "columns": [
        {
            "as": null,
            "expr": {
                "column": "name",
                "table": "syscolumns",
                "type": "column_ref"
            }
        },
        {
            "as": "rowNo",
            "expr": {
                "args": {
                    "type": "expr_list",
                    "value": [
                    ]
                },
                "name": "ROW_NUMBER",
                "over": {
                    "orderby": [
                        {
                            "expr": {
                                "column": "colid",
                                "table": null,
                                "type": "column_ref"
                            },
                            "type": "ASC"
                        }
                    ],
                    "partitionby": [
                        {
                            "as": null,
                            "expr": {
                                "column": "id",
                                "table": null,
                                "type": "column_ref"
                            }
                        }
                    ]
                },
                "type": "function"
            }
        }
    ],
    "distinct": null,
    "from": [
        {
            "as": null,
            "db": null,
            "table": "sysColumns"
        }
    ],
    "groupby": null,
    "having": null,
    "limit": null,
    "options": null,
    "orderby": null,
    "top": null,
    "type": "select",
    "where": null,
    "with": null
}
```

Converted back to T-SQL:
`const sql = parser.sqlify(ast, {database: 'TransactSQL'});`

```
SError: unknown over type
    at B (C:\projects\SQLParser\node_modules\node-sql-parser\index.js:1:1085075)
    at Object.V [as function] (C:\projects\SQLParser\node_modules\node-sql-parser\index.js:1:1086132)
    at wr (C:\projects\SQLParser\node_modules\node-sql-parser\index.js:1:1095810)
    at C:\projects\SQLParser\node_modules\node-sql-parser\index.js:1:1101662
    at C:\projects\SQLParser\node_modules\node-sql-parser\index.js:1:1101974
    at Array.map (<anonymous>)
    at $r (C:\projects\SQLParser\node_modules\node-sql-parser\index.js:1:1101558)
    at lr (C:\projects\SQLParser\node_modules\node-sql-parser\index.js:1:1092014)
    at Zr (C:\projects\SQLParser\node_modules\node-sql-parser\index.js:1:1111238)
    at Jr (C:\projects\SQLParser\node_modules\node-sql-parser\index.js:1:1112115)
```

**Comment by taozhi8833998** [comment]
@MarkSak fixed in #1066
