### ISSUE TITLE
FOR XML Causes Parsing Error in TSQL

### ISSUE THREAD

**Issue by sirosenf** [taozhi8833998/node-sql-parser#1093]
**Describe the bug**
A parsing error is thrown when attempting to generate an AST for a query using [FOR XML](https://docs.microsoft.com/en-us/sql/relational-databases/xml/for-xml-sql-server?view=sql-server-ver16)

**Database Engine**
TransactSQL

**To Reproduce**
-the SQL that be parsed:

```
SELECT Cust.CustomerID,
       OrderHeader.CustomerID,
       OrderHeader.SalesOrderID,
       OrderHeader.Status
FROM Sales.Customer Cust 
INNER JOIN Sales.SalesOrderHeader OrderHeader
ON Cust.CustomerID = OrderHeader.CustomerID
FOR XML AUTO;
```

```
SELECT Cust.CustomerID,
       OrderHeader.CustomerID,
       OrderHeader.SalesOrderID,
       OrderHeader.Status
FROM Sales.Customer Cust 
INNER JOIN Sales.SalesOrderHeader OrderHeader
ON Cust.CustomerID = OrderHeader.CustomerID
FOR XML AUTO;
```

-the node-sql-parser version
4.4
-the node version
16

**Expected behavior**
Proper parsing of the query without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/16842242/184213809-0241a557-222a-4a54-b4df-6f3104888488.png)

**Additional context**
Error Thrown:

> Expected "!=", "#", "%", "(", "*", "+", ",", "-", "--", "/", "/*", ";", "<", "<=", "<>", "=", ">", ">=", "AND", "FULL", "GO", "GROUP", "HAVING", "INNER", "JOIN", "LEFT", "LIMIT", "OR", "ORDER", "RIGHT", "UNION", "WHERE", [ \t\n\r], or end of input but "F" found.

**Comment by mdora7** [comment]
-The complex syntax
I also can proof with the following syntax as well;
  (SELECT TOP 1
        STUFF((
        SELECT DISTINCT CASE WHEN T1.FICHENO != '' THEN ',' + CAST(T1.FICHENO AS VARCHAR(MAX))
        WHEN T1.FICHENO != '' THEN ',' + CAST(T1.FICHENO AS VARCHAR(MAX))
        ELSE NULL
        END
        FROM LG_#_LogoOrganizationId_#_#_LogoTermId_#_STFICHE T1
        WHERE T1.INVNO = T2.FICHENO
        FOR XML PATH('')),1,1,'') DespatchReference
        FROM LG_#_LogoOrganizationId_#_#_LogoTermId_#_INVOICE T2
         WHERE T2.FICHENO = INV.FICHENO 
        AND T2.TRCODE NOT IN (9) ) AS DespatchReference ,

**Comment by dansomething** [comment]
I can confirm the same issue with a TSQL query that uses a CAST.

```sql
INSERT [dbo].[testtable] ([NodeID], [Timestamp], [ResponseTime], [PercentLoss], [Availability], [Weight]) VALUES (2, CAST(N'2023-04-11T22:17:13.0864249' AS DateTime2), 0, 0, 100, 120)
```

```bash
s [SyntaxError]: Expected "#", "(", "--", "/*", "]", or [ \t\n\r] but ")" found.
    at Yu (/home/**/node_modules/node-sql-parser/index.js:1:946951)
    at Object.parse [as transactsql] (/home/**/node_modules/node-sql-parser/index.js:1:1072585)
    at r.value (/home/**/node_modules/node-sql-parser/index.js:1:1250439)
    at r.value (/home/**/node_modules/node-sql-parser/index.js:1:1249996)
    at Object.<anonymous> (/home/**/test.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  expected: [
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: ']', ignoreCase: false },
    { type: 'literal', text: '(', ignoreCase: false },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: ']', ignoreCase: false },
    { type: 'literal', text: '(', ignoreCase: false },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: ']', ignoreCase: false },
    { type: 'literal', text: '(', ignoreCase: false },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: ']', ignoreCase: false },
    { type: 'literal', text: '(', ignoreCase: false }
  ],
  found: ')',
  location: {
    start: { offset: 183, line: 1, column: 184 },
    end: { offset: 184, line: 1, column: 185 }
  }
}

Node.js v18.16.0
```
