### ISSUE TITLE
mysql type longblob not work

### ISSUE THREAD

**Issue by hyoban** [taozhi8833998/node-sql-parser#1109]
**Describe the bug**

```
SyntaxError: Expected "#", "--", "->", "->>", ".", "/*", "BIGINT", "BIT", "CHAR", "DATE", "DATETIME", "DECIMAL", "DOUBLE", "ENUM", "FLOAT", "INT", "INTEGER", "JSON", "LONGTEXT", "MEDIUMTEXT", "NUMERIC", "SMALLINT", "TEXT", "TIME", "TIMESTAMP", "TINYINT", "TINYTEXT", "VARCHAR", "binary", "boolean", "varbinary", or [ \t\n\r] but "l" found.
    at Ou (https://unpkg.com/node-sql-parser/umd/index.umd.js:1:425897)
    at Object.parse [as mysql] (https://unpkg.com/node-sql-parser/umd/index.umd.js:1:553323)
    at r.value (https://unpkg.com/node-sql-parser/umd/index.umd.js:1:67046)
    at r.value (https://unpkg.com/node-sql-parser/umd/index.umd.js:1:66661)
    at window.onload (file:///C:/Users/Hyoban/Desktop/index.html:14:28)
```

**Database Engine**
MySQL

**To Reproduce**

```sql
CREATE TABLE `undo_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `branch_id` bigint(20) NOT NULL,
  `xid` varchar(100) NOT NULL,
  `context` varchar(128) NOT NULL,
  `rollback_info` longblob NOT NULL,
  `log_status` int(11) NOT NULL,
  `log_created` datetime NOT NULL,
  `log_modified` datetime NOT NULL,
  `ext` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `ux_undo_log` (`xid`,`branch_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
```

- the node-sql-parser version `4.4.0`
- the node version `16.16.0`

**Comment by taozhi8833998** [comment]
@hyoban please upgrade to the `4.5.0` version.

**Comment by hyoban** [comment]
@taozhi8833998 tanks!!!! i will check it as soon
