### ISSUE TITLE
columns that are called 'status' cause parser to error out mysteriously

### ISSUE THREAD

**Issue by JesseCastro** [taozhi8833998/node-sql-parser#121]
I managed to figure this issue out because there is a good error message for when you *alias* something as status, but not when the column is named status.  It seems like keyword status nearly anywhere in the query will cause an error.  Suggest maybe adding in a more descriptive error message for when this happens.  
Note - I am using the github version of the module to take advantage of the INSERT..SELECT functionality until such time as 1.6.7 is published.  Unsure if this is in both versions or not.  
Ex:
```
const { Parser } = require('node-sql-parser');
const parser = new Parser();

parser.parse('SELECT status FROM tbl WHERE 1 = 1');
```

Gives error message as follows:
```
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected [A-Za-z0-9_:] or [A-Za-z0-9_] but " " found.
    at peg$buildStructuredError (/Users/jess1447/churn/app2/local_modules/node-sql-parser/build/mysql.js:1735:12)
    at Object.peg$parse [as mysql] (/Users/jess1447/churn/app2/local_modules/node-sql-parser/build/mysql.js:17748:11)
    at Parser.parse (/Users/jess1447/churn/app2/local_modules/node-sql-parser/lib/parser.js:43:50)
    at Object.<anonymous> (/Users/jess1447/churn/app2/ex.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
```

**Comment by JesseCastro** [comment]
I had forgotten...  Status is a reserved word in MySQL...
