### ISSUE TITLE
CREATE TABLE Parse error

### ISSUE THREAD

**Issue by turtle0617** [taozhi8833998/node-sql-parser#131]
Hi, I try to parse this sql but got error.
I found https://github.com/taozhi8833998/node-sql-parser/issues/63  look like resolve,
so I downgrade to version 1.5.0 and try that issue, but also got error.

Hope you can fix the issue, and thanks your contribution.
input:
```
// const grammar = "CREATE TABLE customer ( id int not NULL, name varchar(20) not NULL, primary key(id) ) engine=innodb CHARSET=utf8;";

const ast = parser.astify(grammar);
```
output:
```
/node_modules/node-sql-parser/build/pegjs-parser.js:371
            keyword: kc.toLowerCase(),
                        ^

TypeError: Cannot read property 'toLowerCase' of null
    at peg$c43 (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/build/pegjs-parser.js:371:25)
    at peg$parseconstraint_name (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/build/pegjs-parser.js:3414:18)
    at peg$parsecreate_constraint_primary (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/build/pegjs-parser.js:3440:10)
    at peg$parsecreate_constraint_definition (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/build/pegjs-parser.js:3384:10)
    at peg$parsecreate_definition (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/build/pegjs-parser.js:2376:16)
    at peg$parsecreate_table_definition (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/build/pegjs-parser.js:2310:24)
    at peg$parsecreate_table_stmt (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/build/pegjs-parser.js:1978:31)
    at peg$parsecmd_stmt (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/build/pegjs-parser.js:1734:12)
    at peg$parsecrud_stmt (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/build/pegjs-parser.js:1771:20)
    at peg$parsemultiple_stmt (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/build/pegjs-parser.js:1788:10)
```

**Comment by taozhi8833998** [comment]
Sorry for this bug, I have fixed it already, try the new `1.6.8` version. If it stills there, reopen this issue. Thanks for ur usage.
