### ISSUE TITLE
CREATE TABLE Parse error

### ISSUE THREAD

**Issue by turtle0617** [taozhi8833998/node-sql-parser#134]
Hi ,thank for your fix https://github.com/taozhi8833998/node-sql-parser/issues/131 . but I still can resolve that code and I can't reopen  ,so I open a new one.

I update to `1.6.8` and run that issue , the `lowercase` look like resolve, but I got another error.

input:
```
const grammar = "CREATE TABLE customer ( id int not NULL, name varchar(20) not NULL, primary key(id) ) engine=innodb CHARSET=utf8;";

const ast = parser.astify(grammar);
```

output:
```
node_modules/node-sql-parser/build/mysql.js:17749
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "#", "(", ",", "--", "/*", ";", "AS", "AUTO_INCREMENT", "AVG_ROW_LENGTH", "CHARACTER SET", "COLLATE", "COMMENT", "COMPRESSION", "CONNECTION", "DEFAULT", "ENGINE", "IGNORE", "KEY_BLOCK_SIZE", "MAX_ROWS", "MIN_ROWS", "REPLACE", "SELECT", "STATS_SAMPLE_PAGES", "WITH", [ \t\n\r], or end of input but "C" found.
    at peg$buildStructuredError (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/build/mysql.js:1739:12)
    at Object.peg$parse [as mysql] (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/build/mysql.js:17749:11)
    at Parser.parse (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/lib/parser.js:43:50)
    at Parser.astify (/Users/turtle/Desktop/CodeMirror/node_modules/node-sql-parser/lib/parser.js:28:26)
    at Object.<anonymous> (/Users/turtle/Desktop/CodeMirror/test.js:11:20)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```
I try to use your extract packages `flora-sql-parser`, but got the same error.
Hope this info helps for you and thanks again your contribution.
`flora-sql-parser` output:
```
node_modules/flora-sql-parser/build/pegjs-parser.js:11522
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "$", "(", "--", "/*", "INSERT", "REPLACE", "SELECT", "UPDATE", "WITH", "return", [ \t\n\r], or end of input but "C" found.
    at peg$buildStructuredError (/Users/turtle/Desktop/CodeMirror/node_modules/flora-sql-parser/build/pegjs-parser.js:1019:12)
    at peg$parse (/Users/turtle/Desktop/CodeMirror/node_modules/flora-sql-parser/build/pegjs-parser.js:11522:11)
    at Parser.parse (/Users/turtle/Desktop/CodeMirror/node_modules/flora-sql-parser/lib/parser.js:7:16)
    at Object.<anonymous> (/Users/turtle/Desktop/CodeMirror/test2.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
```

**Comment by taozhi8833998** [comment]
ok, you are using `CHARSET`, while `CHARACTER SET` is supported currently. I would add it later.

**Comment by taozhi8833998** [comment]
sorry for the missing part and bad experience, try `1.6.9` version. I would't close this issue until you confim it has been fixed already

**Comment by turtle0617** [comment]
It can parse success in `1.6.9` now
Thank you so much for fix this issue.

**Comment by taozhi8833998** [comment]
ok, I will close this issue. If you have any more questions about this module, open a new one
