### ISSUE TITLE
astify fails when "recursive" is lowercase

### ISSUE THREAD

**Issue by Newbie012** [taozhi8833998/node-sql-parser#1375]
**Describe the bug**

While writing a query that has `with recursive` fails:
```sql
with recursive number_sequence as (
    SELECT 1
)
SELECT *
FROM number_sequence;
```

```
SyntaxError: Expected "#", "(", "--", "/*", "AS", or [ \t\n\r] but "n" found.
    at Ns (.../node-sql-parser@4.6.6/node_modules/node-sql-parser/build/mysql.js:1:11379)
    at Object.parse (.../node-sql-parser@4.6.6/node_modules/node-sql-parser/build/mysql.js:1:155694)
    at r2.value (.../node-sql-parser@4.6.6/node_modules/node-sql-parser/build/mysql.js:1:194485)
    at r2.value (.../node-sql-parser@4.6.6/node_modules/node-sql-parser/build/mysql.js:1:194043)
    at test (/home/eliya/projects/mysafeql/index.ts:5:24)
    at query (/home/eliya/projects/mysafeql/index.ts:17:1)
    at Object.<anonymous> (/home/eliya/projects/mysafeql/index.ts:17:11)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Object.F (.../@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
```

To fix that, I need to uppercase `recursive`:
```sql
with RECURSIVE number_sequence as (
    SELECT 1
)
SELECT *
FROM number_sequence;
```

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed:
```sql
with recursive number_sequence as (
    SELECT 1
)
SELECT *
FROM number_sequence;
```

-the node-sql-parser version

4.6.6

-the node version

18.4.0

**Expected behavior**
should not fail

**Screenshots**
Reproduction - https://stackblitz.com/edit/js-cduzkg?file=index.js

**Additional context**

**Comment by Newbie012** [comment]
After reading a bit, I think I was wrong about `RECURSIVE` and it has to be uppercase.
