### ISSUE TITLE
Chinese column name

### ISSUE THREAD

**Issue by jingsam** [taozhi8833998/node-sql-parser#145]
I notice some inconsistent  with Chinese column names:

```js
const sql = 'select 中文1 AS 中文2 from a where 中文3 = 1'
const { ast, tableList, columnList } = parser.parse(sql, { database: 'postgresql'})
const formattedSQL = parser.sqlify(sql, { database: 'postgresql'})
```

I get error:

```
/Users/jingsam/projects/tests/node-sql-parser/node_modules/node-sql-parser/build/postgresql.js:17966
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "#", "'", "--", "/*", "\"", "`", [ \t\n\r], or [A-Za-z_] but "中" found.
    at peg$buildStructuredError (/Users/jingsam/projects/tests/node-sql-parser/node_modules/node-sql-parser/build/postgresql.js:1759:12)
    at Object.peg$parse [as postgresql] (/Users/jingsam/projects/tests/node-sql-parser/node_modules/node-sql-parser/build/postgresql.js:17966:11)
    at Parser.parse (/Users/jingsam/projects/tests/node-sql-parser/node_modules/node-sql-parser/lib/parser.js:43:50)
    at Object.<anonymous> (/Users/jingsam/projects/tests/node-sql-parser/index.js:7:47)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

Try this:
```
const sql = 'select "中文1" AS "中文2" from a where "中文3" = 1'
```

I get:

```sql
SELECT '中文1' AS `中文2` FROM "a" WHERE '中文3' = 1
```

I expected all columns should be quoted with `"中文"`

**Comment by taozhi8833998** [comment]
I won't treat it as an issue currently, you'd better not use Chinese as a column name.
