### ISSUE TITLE
Error parsing sql with character sequence

### ISSUE THREAD

**Issue by pidgeonman** [taozhi8833998/node-sql-parser#177]
I'm getting an error when trying to parse a particular SQL with a character sequence that I tracked down to:

`INSERT INTO `posts` (`content`) VALUES('\'s ');`

The error it returns is:

`SyntaxError: Expected "'", "\\", "\\'", "\\/", "\\\"", "\\\\", "\\b", "\\f", "\\n", "\\r", "\\t", "\\u", or [^'\\\0-\x1F\x7F] but "\x03" found.
    at peg$buildStructuredError (/home/something/node_modules/node-sql-parser/build/mysql.js:1748:12)
    at Object.peg$parse [as mysql] (/home/something/node_modules/node-sql-parser/build/mysql.js:17823:11)
    at Parser.parse (/home/something/node_modules/node-sql-parser/lib/parser.js:43:50)
    at Parser.astify (/home/something/node_modules/node-sql-parser/lib/parser.js:28:26)`

Thanks for looking into this!

**Comment by pidgeonman** [comment]
Raw content here https://pastebin.com/k68GHLhQ

**Comment by pidgeonman** [comment]
Running version 1.6.11

**Comment by taozhi8833998** [comment]
Do you really need to store `ETX `, the char after `\s`,  to the database ???

**Comment by pidgeonman** [comment]
We run a CMS, so we must store whatever comes from the user and make no distinction. If the database and mysqldump don't break when processing it, why should the parser break? We appreciate your help fixing this case.

**Comment by taozhi8833998** [comment]
try `1.6.22`
