### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by MayamaTakeshi** [taozhi8833998/node-sql-parser#1906]
I am trying to run "npm test" but I get:
```
 WEBPACK  Compiling... : timing npm:load Completed in 37ms

  [=========================] 100% (completed)

 WEBPACK  Compiled successfully in 13613ms

 MOCHA  Testing...

 RUNTIME EXCEPTION  Exception occurred while loading your tests

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/takeshi/src/git/node-sql-parser/node_modules/chai/chai.js from /home/takeshi/src/git/node-sql-parser/output/dev/main.js not supported.
Instead change the require of chai.js in /home/takeshi/src/git/node-sql-parser/output/dev/main.js to a dynamic import() which is available in all CommonJS modules.
    at Object.module_1.default._extensions.<computed> [as .js] (/home/takeshi/src/git/node-sql-parser/node_modules/mochapack/lib/util/registerRequireHook.js:90:71)
    at Object.chai (/home/takeshi/src/git/node-sql-parser/output/dev/main.js:455243:18)
    at __webpack_require__ (/home/takeshi/src/git/node-sql-parser/output/dev/main.js:749:30)
    at fn (/home/takeshi/src/git/node-sql-parser/output/dev/main.js:60:20)
    at Object../test/ast.spec.js (/home/takeshi/src/git/node-sql-parser/output/dev/main.js:448582:16)
    at __webpack_require__ (/home/takeshi/src/git/node-sql-parser/output/dev/main.js:749:30)
    at fn (/home/takeshi/src/git/node-sql-parser/output/dev/main.js:60:20)
    at run (/home/takeshi/src/git/node-sql-parser/output/dev/main.js:830:20)
    at Array.forEach (<anonymous>)
    at Object../node_modules/mochapack/lib/entry.js (/home/takeshi/src/git/node-sql-parser/output/dev/main.js:836:24)
    at __webpack_require__ (/home/takeshi/src/git/node-sql-parser/output/dev/main.js:749:30)
    at /home/takeshi/src/git/node-sql-parser/output/dev/main.js:816:75
    at Object.<anonymous> (/home/takeshi/src/git/node-sql-parser/output/dev/main.js:819:10)
    at Object.module_1.default._extensions.<computed> [as .js] (/home/takeshi/src/git/node-sql-parser/node_modules/mochapack/lib/util/registerRequireHook.js:95:16)
    at /home/takeshi/src/git/node-sql-parser/node_modules/mocha/lib/mocha.js:414:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/takeshi/src/git/node-sql-parser/node_modules/mocha/lib/mocha.js:411:14)
    at Mocha.run (/home/takeshi/src/git/node-sql-parser/node_modules/mocha/lib/mocha.js:972:10)
    at /home/takeshi/src/git/node-sql-parser/node_modules/mochapack/lib/runner/TestRunner.js:150:53
    at /home/takeshi/src/git/node-sql-parser/node_modules/mochapack/lib/webpack/compiler/registerReadyCallback.js:13:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/takeshi/src/git/node-sql-parser/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at AsyncSeriesHook.lazyCompileHook (/home/takeshi/src/git/node-sql-parser/node_modules/tapable/lib/Hook.js:154:20)
    at /home/takeshi/src/git/node-sql-parser/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/home/takeshi/src/git/node-sql-parser/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/takeshi/src/git/node-sql-parser/node_modules/webpack/lib/Compiler.js:298:10
    at /home/takeshi/src/git/node-sql-parser/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/takeshi/src/git/node-sql-parser/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/takeshi/src/git/node-sql-parser/node_modules/tapable/lib/Hook.js:154:20)
    at /home/takeshi/src/git/node-sql-parser/node_modules/webpack/lib/Compiler.js:482:27
    at /home/takeshi/src/git/node-sql-parser/node_modules/neo-async/async.js:2818:7
    at done (/home/takeshi/src/git/node-sql-parser/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/takeshi/src/git/node-sql-parser/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /home/takeshi/src/git/node-sql-parser/node_modules/webpack/lib/Compiler.js:464:33
    at MemoryFileSystem.writeFile (/home/takeshi/src/git/node-sql-parser/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/home/takeshi/src/git/node-sql-parser/node_modules/webpack/lib/Compiler.js:462:30)
    at /home/takeshi/src/git/node-sql-parser/node_modules/webpack/lib/Compiler.js:476:7
    at arrayIterator (/home/takeshi/src/git/node-sql-parser/node_modules/neo-async/async.js:3467:9)
    at done (/home/takeshi/src/git/node-sql-parser/node_modules/neo-async/async.js:3527:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/takeshi/src/git/node-sql-parser/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/takeshi/src/git/node-sql-parser/node_modules/tapable/lib/Hook.js:154:20)
    at /home/takeshi/src/git/node-sql-parser/node_modules/webpack/lib/Compiler.js:464:33
    at MemoryFileSystem.writeFile (/home/takeshi/src/git/node-sql-parser/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/home/takeshi/src/git/node-sql-parser/node_modules/webpack/lib/Compiler.js:462:30)
    at /home/takeshi/src/git/node-sql-parser/node_modules/webpack/lib/Compiler.js:476:7
    at arrayIterator (/home/takeshi/src/git/node-sql-parser/node_modules/neo-async/async.js:3467:9)
    at timesSync (/home/takeshi/src/git/node-sql-parser/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/home/takeshi/src/git/node-sql-parser/node_modules/neo-async/async.js:3463:5)
    at emitFiles (/home/takeshi/src/git/node-sql-parser/node_modules/webpack/lib/Compiler.js:358:13)
    at Immediate._onImmediate (/home/takeshi/src/git/node-sql-parser/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)

npm timing command:run-script Completed in 17417ms
npm timing command:test Completed in 17420ms
npm timing npm Completed in 17463ms
```
I am using node v16.17.1 because on v21, 'npm run build' fails.

**Comment by MayamaTakeshi** [comment]
It is OK now. Thanks.
