### ISSUE TITLE
[FlinkSQL] `CREATE ... WITH ('key' = 'value')` not supported

### ISSUE THREAD

**Issue by mserranom** [taozhi8833998/node-sql-parser#2120]
**Describe the bug**

`CREATE ` statements in Flink accept key/value options using `WITH`, as in:

```sql
CREATE TABLE MyTable (
  `user_id` BIGINT,
  `name` STRING,
  `timestamp` TIMESTAMP_LTZ(3) METADATA   
) WITH (
  'connector' = 'kafka'
  ...
);
```

The parser however, is unable to parse a statement of this kind.

**Database Engine**

FlinkSQL

**To Reproduce**

Added the following test cases to https://github.com/taozhi8833998/node-sql-parser/blob/9cc0b34745a7baeed509efd8487ee5e4f5cd0586/test/flink.spec.js:

```javascript
 {
      title: "create table",
      sql: [
        "CREATE TABLE Orders (`user` BIGINT)",
        "CREATE TABLE `Orders` (`user` BIGINT)",
      ],
    },
    {
      title: "create table with options",
      sql: [
        "CREATE TABLE Orders (`user` BIGINT) WITH ('connector' = 'kafka')",
        "CREATE TABLE `Orders` (`user` BIGINT) WITH ('connector' = 'kafka')",
      ],
    }
```

The first test succeeds, the second fails with:

```
  1) Flink
       should support create table:
     SyntaxError: Expected "'", "--", "/*", "RECURSIVE", "\"", [ \t\n\r], or [A-Za-z_一-龥] but "(" found.
      at peg$buildStructuredError (pegjs/flinksql.pegjs:3344:1)
      at Object.peg$parse [as flinksql] (pegjs/flinksql.pegjs:28884:1)
      at Parser.parse (src/parser.js:26:52)
      at Parser.astify (src/parser.js:8:26)
      at getParsedSql (test/flink.spec.js:12:26)
      at Context.<anonymous> (test/flink.spec.js:434:14)
      at processImmediate (node:internal/timers:478:21)
```

- the node-sql-parser version: `5.3.2`
- the node version: `v20.12.2`

**Expected behavior**

Should be able to parse `WITH ('key' = 'value')` in `CREATE` statements

**Comment by mserranom** [comment]
Brilliant, thanks!
