### ISSUE TITLE
Unable to Parse with "TOP" keyword

### ISSUE THREAD

**Issue by Mobackilayarajaselvaraj** [taozhi8833998/node-sql-parser#213]
`SELECT TOP 3 * FROM Customers`

```
ERROR 

peg$SyntaxError {message: "Expected "!=", "#", "%", "&&", "'", "(", "*", "+",…t\n\r], [A-Za-z_], or end of input but "3" found.", expected: Array(292), found: "3", location: {…}, name: "SyntaxError", …}
message: "Expected "!=", "#", "%", "&&", "'", "(", "*", "+", ",", "-", "--", ".", "/", "/*", ";", "<", "<=", "<>", "=", ">", ">=", "AND", "AS", "BETWEEN", "FROM", "GROUP", "HAVING", "IN", "IS", "LIKE", "LIMIT", "NOT", "OR", "ORDER", "UNION", "WHERE", "\"", "`", "||", [ \t\n\r], [A-Za-z_], or end of input but "3" found."
expected: (292) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, …]
found: "3"
location: {start: {…}, end: {…}}
name: "SyntaxError"
ngDebugContext: DebugContext_ {view: {…}, nodeIndex: 0, nodeDef: {…}, elDef: {…}, elView: {…}}
ngErrorLogger: ƒ ()
stack: "SyntaxError: Expected "!=", "#", "%", "&&", "'", "(", "*", "+", ",", "-", "--", ".", "/", "/*", ";", "<", "<=", "<>", "=", ">", ">=", "AND", "AS", "BETWEEN", "FROM", "GROUP", "HAVING", "IN", "IS", "LIKE", "LIMIT", "NOT", "OR", "ORDER", "UNION", "WHERE", "\"", "`", "||", [ \t\n\r], [A-Za-z_], or end of input but "3" found.↵    at peg$buildStructuredError (https://angular-material-5-2-1-starter-xhtdfx.stackblitz.io/turbo_modules/node-sql-parser@1.7.1/build/mysql.js:1862:12)↵    at Object.peg$parse [as mysql] (https://angular-material-5-2-1-starter-xhtdfx.stackblitz.io/turbo_modules/node-sql-parser@1.7.1/build/mysql.js:18997:11)↵    at Parser.parse (https://angular-material-5-2-1-starter-xhtdfx.stackblitz.io/turbo_modules/node-sql-parser@1.7.1/lib/parser.js:49:50)↵    at Parser.astify (https://angular-material-5-2-1-starter-xhtdfx.stackblitz.io/turbo_modules/node-sql-parser@1.7.1/lib/parser.js:34:26)↵    at AppComponent.ngOnInit (https://angular-material-5-2-1-starter-xhtdfx.stackblitz.io/~/app/app.component.ts:25:23)↵    at checkAndUpdateDirectiveInline (https://angular-material-5-2-1-starter-xhtdfx.stackblitz.io/turbo_modules/@angular/core@5.2.7/bundles/core.umd.js:12407:19)↵    at checkAndUpdateNodeInline (https://angular-material-5-2-1-starter-xhtdfx.stackblitz.io/turbo_modules/@angular/core@5.2.7/bundles/core.umd.js:13931:20)↵    at checkAndUpdateNode (https://angular-material-5-2-1-starter-xhtdfx.stackblitz.io/turbo_modules/@angular/core@5.2.7/bundles/core.umd.js:13874:16)↵    at debugCheckAndUpdateNode (https://angular-material-5-2-1-starter-xhtdfx.stackblitz.io/turbo_modules/@angular/core@5.2.7/bundles/core.umd.js:14767:76)↵    at debugCheckDirectivesFn (https://angular-material-5-2-1-starter-xhtdfx.stackblitz.io/turbo_modules/@angular/core@5.2.7/bundles/core.umd.js:14708:13)"
__proto__: Error
```

**Comment by taozhi8833998** [comment]
This is Access database grammar???

**Comment by taozhi8833998** [comment]
try using 

```javascript
const opt = {
   database: 'transactsql'
}
const sql = 'select top 3 * from tableA'
const ast = parser.astify(sql, opt)
```
in `1.7.2` version

**Comment by Mobackilayarajaselvaraj** [comment]
@taozhi8833998 Thanks. It worked :)

**Comment by taozhi8833998** [comment]
ok, I will close this issue.
