### ISSUE TITLE
TSQL comment not supported

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#292]
**Describe the bug**
When using a comment with transactsql the parser throws an error

**Database Engine**
transactsql

**To Reproduce**
-the SQL that be parsed
```js
const { Parser } = require("node-sql-parser");
const parser = new Parser();
const ast = parser.astify(`-- +migrate Up`, { database: "transactsql" });
console.log(ast);
```

-the node-sql-parser version
1.9.2
-the node version
12.16.3

**Expected behavior**
No error since this is valid tsql

**Screenshots**

**Additional context**
```
/Users/xxx/xxx/xxx/node-sql-parser/node_modules/node-sql-parser/build/transactsql.js:20031
      throw peg$buildStructuredError(
      ^
peg$SyntaxError: Expected "#", "$", "--", "/*", ";", "@", "@@", "SELECT", "WITH", "return", [ \t\n\r], or [A-Za-z_] but end of input found.
    at peg$buildStructuredError (/Users/ethan/work/projects/node-sql-parser/node_modules/node-sql-parser/build/transactsql.js:1953:14)
    at Object.peg$parse [as transactsql] (/Users/ethan/work/projects/node-sql-parser/node_modules/node-sql-parser/build/transactsql.js:20031:13)
    at Parser.parse (/Users/ethan/work/projects/node-sql-parser/node_modules/node-sql-parser/lib/parser.js:49:52)
    at Parser.astify (/Users/ethan/work/projects/node-sql-parser/node_modules/node-sql-parser/lib/parser.js:34:28)
    at Object.<anonymous> (/Users/ethan/work/projects/node-sql-parser/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  expected: [
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'WITH', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'WITH', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'SELECT', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '@@', ignoreCase: false },
    { type: 'literal', text: '@', ignoreCase: false },
    { type: 'literal', text: '$', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: 'return', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: ';', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'WITH', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'WITH', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'SELECT', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '@@', ignoreCase: false },
    { type: 'literal', text: '@', ignoreCase: false },
    { type: 'literal', text: '$', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: 'return', ignoreCase: true }
  ],
  found: null,
  location: {
    start: { offset: 14, line: 1, column: 15 },
    end: { offset: 14, line: 1, column: 15 }
  }
}

```

**Comment by esetnik** [comment]
Related to #174

**Comment by taozhi8833998** [comment]
comment only???

**Comment by taozhi8833998** [comment]
@esetnik `sql` is required in content.

try

```sql
-- +migrate Up .  
SELECT *  
FROM Person.Address  
ORDER BY PostalCode ASC; -- SQL is required in context
-- that is the default.
```

**Comment by taozhi8833998** [comment]
@esetnik I will close the issue since the parsed content don't contain any valid SQL. If you have any more comments on this, you could reopen it, and discuss it.

**Comment by esetnik** [comment]
@taozhi8833998 thank you for your feedback. In Microsoft SQL Server management studio you can create a "comment-only" SQL statement and execute it without issue. So I believe this issue should be reopened as the error is not consistent with the official tooling built by Microsoft. Thanks again.

![image](https://user-images.githubusercontent.com/664434/81576652-84b37980-9376-11ea-99b1-428fbfb492a1.png)

**Comment by esetnik** [comment]
Also I think it's still not working with the following `CREATE TABLE`. This is showing an error for me.

```sql
-- +migrate Up
CREATE TABLE quiz (
  id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
);
```

**Comment by taozhi8833998** [comment]
ok, I will check it again later. Thanks for ur feedback.

**Comment by taozhi8833998** [comment]
try `1.10.1`

**Comment by esetnik** [comment]
Working well, thanks!

**Comment by esetnik** [comment]
Actually I'm seeing the same issue with comments and insert statements in v10.1.1:

```sql
-- +migrate Up
-- +migrate StatementBegin
INSERT INTO test 
(name, max_attempts, num_questions, passing_score)
VALUES ('quiz', 3, 10, 70);
```
