### ISSUE TITLE
TSQL IDENTITY not supported

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#293]
**Describe the bug**
When creating a table with an `IDENTITY` column e.g. `id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1)`

**Database Engine**
transactsql

**To Reproduce**
-the SQL that be parsed
```js
const { Parser } = require("node-sql-parser");
const parser = new Parser();
const ast = parser.astify(
  `CREATE TABLE test (
  id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1)
);`,
  { database: "transactsql" }
);
console.log(ast);
```

-the node-sql-parser version
1.9.2
-the node version
12.16.3

**Expected behavior**
This is valid tsql, no error should be thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/664434/81328512-0ea7cd80-906b-11ea-954b-441a54bcd5ed.png)

**Additional context**
```

/Users/ethan/work/projects/node-sql-parser/node_modules/node-sql-parser/build/transactsql.js:20031
      throw peg$buildStructuredError(
      ^
peg$SyntaxError: Expected "#", ")", ",", "--", "/*", "COLLATE", "COLUMN_FORMAT", "COMMENT", "REFERENCES", "STORAGE", or [ \t\n\r] but "I" found.
    at peg$buildStructuredError (/Users/ethan/work/projects/node-sql-parser/node_modules/node-sql-parser/build/transactsql.js:1953:14)
    at Object.peg$parse [as transactsql] (/Users/ethan/work/projects/node-sql-parser/node_modules/node-sql-parser/build/transactsql.js:20031:13)
    at Parser.parse (/Users/ethan/work/projects/node-sql-parser/node_modules/node-sql-parser/lib/parser.js:49:52)
    at Parser.astify (/Users/ethan/work/projects/node-sql-parser/node_modules/node-sql-parser/lib/parser.js:34:28)
    at Object.<anonymous> (/Users/ethan/work/projects/node-sql-parser/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  expected: [
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'COMMENT', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'COLLATE', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'COLUMN_FORMAT', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'STORAGE', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'REFERENCES', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: ',', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: ')', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'COMMENT', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'COLLATE', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'COLUMN_FORMAT', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'STORAGE', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'REFERENCES', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: ',', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: ')', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'COMMENT', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'COLLATE', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'COLUMN_FORMAT', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'STORAGE', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    ... 17 more items
  ],
  found: 'I',
  location: {
    start: { offset: 53, line: 2, column: 34 },
    end: { offset: 54, line: 2, column: 35 }
  }
}
```

**Comment by esetnik** [comment]
TSQL doesn't support AUTOINCREMENT so I think the grammar needs to be modified for IDENTITY. See https://github.com/taozhi8833998/node-sql-parser/blob/fbed1d419a6baf701ec7999b2c0cb700a0084a02/pegjs/transactsql.pegjs#L336

See https://www.w3schools.com/sql/sql_autoincrement.asp

**Comment by taozhi8833998** [comment]
working on it

**Comment by taozhi8833998** [comment]
try `1.10.0`

**Comment by esetnik** [comment]
Thank you!

**Comment by taozhi8833998** [comment]
please feel free to close this issue, if it has been fixed.
