### ISSUE TITLE
bigquery parse issue

### ISSUE THREAD

**Issue by mx2323** [taozhi8833998/node-sql-parser#298]
**Describe the bug**
```code
SELECT *, struct_value
FROM UNNEST(ARRAY<STRUCT<x INT64, y STRING>>[(1, 'foo'), (3, 'bar')])
       AS struct_value;
```
**Database Engine**
BigQuery SQL  (using the default MYSQL)

```code
"SyntaxError: Expected "#", "'", ",", "--", ".", "/*", ";", "AS", "FULL", "GROUP", "HAVING", "INNER", "JOIN", "LEFT", "LIMIT", "ORDER", "RIGHT", "UNION", "WHERE", "\"", "`", [ \t\n\r], [A-Za-z0-9_], [A-Za-z_], or end of input but "(" found.
    at peg$buildStructuredError (https://devel.structure.rest:8080/static/js/0.chunk.js:786559:14)
    at Object.peg$parse [as mysql] (https://devel.structure.rest:8080/static/js/0.chunk.js:807766:13)
    at Parser.parse (https://devel.structure.rest:8080/static/js/0.chunk.js:857411:52)
    at Parser.astify (https://devel.structure.rest:8080/static/js/0.chunk.js:857396:28)
    at https://devel.structure.rest:8080/static/js/main.chunk.js:24416:26
    at commitHookEffectList (https://devel.structure.rest:8080/static/js/0.chunk.js:962367:30)
    at commitPassiveHookEffects (https://devel.structure.rest:8080/static/js/0.chunk.js:962400:15)
    at HTMLUnknownElement.callCallback (https://devel.structure.rest:8080/static/js/0.chunk.js:940694:18)
    at Object.invokeGuardedCallbackDev (https://devel.structure.rest:8080/static/js/0.chunk.js:940743:20)
    at invokeGuardedCallback (https://devel.structure.rest:8080/static/js/0.chunk.js:940796:35)
    at flushPassiveEffectsImpl (https://devel.structure.rest:8080/static/js/0.chunk.js:965736:11)
    at unstable_runWithPriority (https://devel.structure.rest:8080/static/js/0.chunk.js:1012934:16)
    at runWithPriority$2 (https://devel.structure.rest:8080/static/js/0.chunk.js:952588:14)
    at flushPassiveEffects (https://devel.structure.rest:8080/static/js/0.chunk.js:965705:16)
    at performSyncWorkOnRoot (https://devel.structure.rest:8080/static/js/0.chunk.js:964585:9)
    at https://devel.structure.rest:8080/static/js/0.chunk.js:952642:28
    at unstable_runWithPriority (https://devel.structure.rest:8080/static/js/0.chunk.js:1012934:16)
    at runWithPriority$2 (https://devel.structure.rest:8080/static/js/0.chunk.js:952588:14)
    at flushSyncCallbackQueueImpl (https://devel.structure.rest:8080/static/js/0.chunk.js:952637:11)
    at flushSyncCallbackQueue (https://devel.structure.rest:8080/static/js/0.chunk.js:952625:7)
    at batchedUpdates$1 (https://devel.structure.rest:8080/static/js/0.chunk.js:964725:11)
    at Object.notify (https://devel.structure.rest:8080/static/js/0.chunk.js:986689:7)
    at Subscription.notifyNestedSubs (https://devel.structure.rest:8080/static/js/0.chunk.js:986762:20)
    at Subscription.handleChangeWrapper (https://devel.structure.rest:8080/static/js/0.chunk.js:986767:12)
    at dispatch (https://devel.structure.rest:8080/static/js/0.chunk.js:1008846:7)
    at https://devel.structure.rest:8080/static/js/0.chunk.js:106640:17
    at https://devel.structure.rest:8080/static/js/0.chunk.js:106815:16
    at Object.onChange (https://devel.structure.rest:8080/static/js/main.chunk.js:24438:5)
    at ReactAce.onChange (https://devel.structure.rest:8080/static/js/0.chunk.js:932345:18)
    at Editor.EventEmitter._signal (https://devel.structure.rest:8080/static/js/0.chunk.js:240355:60)
    at Editor.onDocumentChange (https://devel.structure.rest:8080/static/js/0.chunk.js:249983:12)
    at EditSession.EventEmitter._signal (https://devel.structure.rest:8080/static/js/0.chunk.js:240355:60)
    at EditSession.onChange (https://devel.structure.rest:8080/static/js/0.chunk.js:246201:12)
    at Document.EventEmitter._signal (https://devel.structure.rest:8080/static/js/0.chunk.js:240355:60)
    at Document.applyDelta (https://devel.structure.rest:8080/static/js/0.chunk.js:244328:14)
    at Document.insertMergedLines (https://devel.structure.rest:8080/static/js/0.chunk.js:244218:12)
    at Document.insert (https://devel.structure.rest:8080/static/js/0.chunk.js:244129:19)
    at EditSession.insert (https://devel.structure.rest:8080/static/js/0.chunk.js:246733:23)
    at Editor.insert (https://devel.structure.rest:8080/static/js/0.chunk.js:250247:15)
    at Editor.$handlePaste (https://devel.structure.rest:8080/static/js/0.chunk.js:250175:28)
    at Object.exec (https://devel.structure.rest:8080/static/js/0.chunk.js:249024:14)
    at https://devel.structure.rest:8080/static/js/0.chunk.js:248389:24
    at CommandManager.EventEmitter._emit.EventEmitter._dispatchEvent (https://devel.structure.rest:8080/static/js/0.chunk.js:240347:55)
    at CommandManager.exec (https://devel.structure.rest:8080/static/js/0.chunk.js:248415:28)
    at Editor.onPaste (https://devel.structure.rest:8080/static/js/0.chunk.js:250157:21)
    at HTMLTextAreaElement.onPaste (https://devel.structure.rest:8080/static/js/0.chunk.js:238793:24)"
```

**Comment by mx2323** [comment]
in general - how hard would it be to support bigquery select statements fully in this library? is that a lot of work?

**Comment by taozhi8833998** [comment]
ok, I will separate the BigQuery from MySQL, and support the syntax.

**Comment by mx2323** [comment]
Oh that’s exciting! Keep me posted - I’ll read up on peg.js and see if I can help.

**Comment by mx2323** [comment]
Would it help if I paste to this issue any of the queries that I find that are currently failing?

**Comment by taozhi8833998** [comment]
> Would it help if I paste to this issue any of the queries that I find that are currently failing?

yes, It would help me a lot, thanks for that.

**Comment by taozhi8833998** [comment]
working on [standard SQL query syntax](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax)...

**Comment by mx2323** [comment]
awesome. 

found a few these come from the query syntax example page https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax

1) _STRUCT data type_ 
```WITH locations AS
  (SELECT STRUCT("Seattle" AS city, "Washington" AS state) AS location
  UNION ALL
  SELECT STRUCT("Phoenix" AS city, "Arizona" AS state) AS location)
SELECT l.location.*
FROM locations l;
```

2) _array data type_ 
```WITH locations AS
  (SELECT ARRAY<STRUCT<city STRING, state STRING>>[("Seattle", "Washington"),
    ("Phoenix", "Arizona")] AS location)
SELECT l.LOCATION[offset(0)].*
FROM locations l;
```


3) _EXCEPT is a keyword_
```WITH orders AS
  (SELECT 5 as order_id,
  "sprocket" as item_name,
  200 as quantity)
SELECT * EXCEPT (order_id)
FROM orders;
```


4) _REPLACE is a keyword_
```WITH orders AS
  (SELECT 5 as order_id,
  "sprocket" as item_name,
  200 as quantity)
SELECT * REPLACE ("widget" AS item_name)
FROM orders;
```

5) _another example of STRUCT, this time as a preceding keyword_
```SELECT AS STRUCT 1 x, 2, 3 x

SELECT AS VALUE STRUCT(1 a, 2 b) xyz FROM Table;

```
https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select_as_struct


6) _FOR SYSTEM_TIME AS OF 
https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#for_system_time_as_of_
```SELECT *
FROM t
  FOR SYSTEM_TIME AS OF TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 HOUR);
```

7) _This one looks tough. an UNNEST with ARRAY, STRUCT in the FROM clause_

```SELECT *
FROM UNNEST(**ARRAY<STRUCT<x INT64, y STRING>>[(1, 'foo'), (3, 'bar')]);
```
8) _apparently there is a parenthesis syntax_
```
 ( SELECT * FROM Roster
  UNION ALL
  SELECT * FROM TeamMascot )
ORDER BY SchoolID;
```
 - this is described in the order by section
https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#order_by_clause_

9) _window clause:_
end: {offset: 60, line: 2, column: 10}
start: {offset: 59, line: 2, column: 9}
message: "Expected "#", "--", "/*", "PARTITION", or [ \t\n\r] but "i" found."

```SELECT item, purchases, category, LAST_VALUE(item)
  OVER (item_window) AS most_popular
FROM Produce
WINDOW item_window AS (
  PARTITION BY category
  ORDER BY purchases
  ROWS BETWEEN 2 PRECEDING AND 2 FOLLOWING)
```

https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#window_clause_


10) _set operators_
```
query1 UNION ALL (query2 UNION DISTINCT query3)
```

https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#set_operators

10) _bigquery allows a final comma in the last column declaration, the parser fails on this last comma_

SELECT season as season,
			academic_year as academic_year, <--- **extra comma here** 
FROM source

**Comment by taozhi8833998** [comment]
@mx2323 I will publish this feature this Sunday, I hope it's not too late for you.

**Comment by mx2323** [comment]
awesome. looking forward to reading the diff!

**Comment by taozhi8833998** [comment]
> awesome. looking forward to reading the diff!

maybe I will just release a new version to the npm registry and don't push the codes to Github in order to disappear the diff.

**Comment by mx2323** [comment]
why would you want to do that? i dont understand.

**Comment by taozhi8833998** [comment]
> why would you want to do that? i dont understand.

It's a joke just for fun. I won't do that. Sorry for making you misunderstand.

**Comment by mx2323** [comment]
no worries  - sounds good!

**Comment by taozhi8833998** [comment]
@mx2323 bear with the next release, I am working on it again.

**Comment by taozhi8833998** [comment]
it has been finished basically, I will add more test cases on it, and continue to solve `sqlify` issue for BigQuery.

**Comment by taozhi8833998** [comment]
@mx2323 I have released a new beta version `2.0.0-beta` to support BigQuery syntax, you can give it a try, any feedbacks are welcome.

**Comment by mx2323** [comment]
nice. trying it out most things work. however -

```
    SELECT win_team_id AS winTeamID, win_market as market, winName as name from winners UNION DISTINCT (SELECT * from losers)
```
```
WITH locations AS
  (SELECT STRUCT("Seattle" AS city, "Washington" AS state) AS location
  UNION ALL
  SELECT STRUCT("Phoenix" AS city, "Arizona" AS state) AS location)
SELECT l.location.*
FROM locations l;
```

```
WITH locations AS
  (SELECT ARRAY<STRUCT<city STRING, state STRING>>[("Seattle", "Washington"),
    ("Phoenix", "Arizona")] AS location)
SELECT l.LOCATION[offset(0)].*
FROM locations l;
```

```
WITH orders AS
  (SELECT 5 as order_id,
  "sprocket" as item_name,
  200 as quantity)
SELECT * EXCEPT (order_id)
FROM orders;
```

```
WITH orders AS
  (SELECT 5 as order_id,
  "sprocket" as item_name,
  200 as quantity)
SELECT * REPLACE ("widget" AS item_name)
FROM orders;
```

```
WITH orders AS
  (SELECT 5 as order_id,
  "sprocket" as item_name,
  200 as quantity)
SELECT * REPLACE (quantity/2 AS quantity)
FROM orders;
```

```
SELECT AS STRUCT 1 x, 2, 3 x
```

```
SELECT AS VALUE STRUCT(1 AS x, 2, 3 AS x)
```


it appears as though many of the examples on the page dont work :(

https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax

**Comment by taozhi8833998** [comment]
got it, this feature is in beta version now, and I will fix it today.

**Comment by taozhi8833998** [comment]
the top three SQLs are supported in `2.0.1-beta` version, the left SQLs were supported in `2.0.1-beta` before.

**Comment by taozhi8833998** [comment]
@mx2323 The SQLs above are supported in `2.0.2-beta` version now, give it a shot.
