### ISSUE TITLE
Cannot parse MySQL UPDATE statements with LIMIT clause

### ISSUE THREAD

**Issue by kpeters-cbsi** [taozhi8833998/node-sql-parser#372]
**Describe the bug**
MySQL UPDATE statements with a LIMIT clause fail to parse.

**Database Engine**
MySQL

**To Reproduce**
- SQL: "update table1 set field1 = 7461, status = 'W' where field2 = (select field2 from table2 where field1 = 7461) and field1 is null limit 5;",
- node-sql-parser: 2.2.3
- node: v12.17.0

**Expected behavior**
```
// demo.js
const NodeSQLParser = require('node-sql-parser')
const parser = new NodeSQLParser.Parser()
const sql = "update table1 set field1 = 7461, status = 'W' where field2 = (select field2 from table2 where field1 = 7461) and field1 is null limit 5;"
const ast = parser.astify(sql)
console.log({ast: ast})
```
Expected parser.astify(sql) to not throw an Error

**Screenshots**
```
$ node demo.js
/home/kit/work/sketches/js/node-sql-parser/node_modules/node-sql-parser/build/mysql.js:20691
      throw peg$buildStructuredError(
      ^
peg$SyntaxError: Expected "#", "%", "*", "+", "-", "--", "/", "/*", ";", "AND", "OR", [ \t\n\r], or end of input but "l" found.
    at peg$buildStructuredError (/home/kit/work/sketches/js/node-sql-parser/node_modules/node-sql-parser/build/mysql.js:2033:14)
    at Object.peg$parse [as mysql] (/home/kit/work/sketches/js/node-sql-parser/node_modules/node-sql-parser/build/mysql.js:20691:13)
    at Parser.parse (/home/kit/work/sketches/js/node-sql-parser/node_modules/node-sql-parser/lib/parser.js:52:52)
    at Parser.astify (/home/kit/work/sketches/js/node-sql-parser/node_modules/node-sql-parser/lib/parser.js:36:28)
    at Object.<anonymous> (/home/kit/work/sketches/js/node-sql-parser/demo.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  expected: [
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '*', ignoreCase: false },
    { type: 'literal', text: '/', ignoreCase: false },
    { type: 'literal', text: '%', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '+', ignoreCase: false },
    { type: 'literal', text: '-', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'AND', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'OR', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: ';', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '*', ignoreCase: false },
    { type: 'literal', text: '/', ignoreCase: false },
    { type: 'literal', text: '%', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '+', ignoreCase: false },
    { type: 'literal', text: '-', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'AND', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'OR', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'end' }
  ],
  found: 'l',
  location: {
    start: { offset: 128, line: 1, column: 129 },
    end: { offset: 129, line: 1, column: 130 }
  }
}
```

**Comment by kpeters-cbsi** [comment]
If someone can explain to me how the parser works, I can submit a patch. I just couldn't make heads or tails of the code.

**Comment by taozhi8833998** [comment]
> If someone can explain to me how the parser works, I can submit a patch. I just couldn't make heads or tails of the code.

I will support it this weekend, sorry for my bad code. The parser is based on [pegjs](https://pegjs.org/), maybe you should learn it first. Thanks for ur issue and kindness.

**Comment by kpeters-cbsi** [comment]
I don't think it's that your code is bad. I think that it's my unfamiliarity with pegjs.

**Comment by kpeters-cbsi** [comment]
Looking at [mysql.pegjs](https://github.com/taozhi8833998/node-sql-parser/blob/master/pegjs/mysql.pegjs), I think all you'd need to do is add an optional `limit_clause` to `update_stmt`. You ought to do that to `delete_stmt` as well, and add `order_by_clause` to both, as both LIMIT and ORDER BY are legal clauses in UPDATE and DELETE statements (see https://dev.mysql.com/doc/refman/5.7/en/update.html)

**Comment by taozhi8833998** [comment]
> Looking at [mysql.pegjs](https://github.com/taozhi8833998/node-sql-parser/blob/master/pegjs/mysql.pegjs), I think all you'd need to do is add an optional `limit_clause` to `update_stmt`. You ought to do that to `delete_stmt` as well, and add `order_by_clause` to both, as both LIMIT and ORDER BY are legal clauses in UPDATE and DELETE statements (see https://dev.mysql.com/doc/refman/5.7/en/update.html)

ok, I am working on it now, I will publish a new version to support this feature.

**Comment by taozhi8833998** [comment]
@kpeters-cbsi try `2.2.4` version.

**Comment by kpeters-cbsi** [comment]
That worked, thanks!
