### ISSUE TITLE
Parse 

### ISSUE THREAD

**Issue by kpeters-cbsi** [taozhi8833998/node-sql-parser#376]
**Describe the bug**
MySQL SELECT statements using the NOT keyword fail to parse

**Database Engine**
MySQL

**To Reproduce**
- SQL: "select id from foo where deleted and not suspended",
- node-sql-parser: 2.2.6
- node: v12.17.0

**Expected behavior**
```
// demo.js
const NodeSQLParser = require('node-sql-parser')
const parser = new NodeSQLParser.Parser()
const sql = 'select id from foo where deleted and not suspended'
const ast = parser.astify(sql)
console.debug({ ast: ast })
```
Expected parser.astify(sql) to not throw an Error

**Screenshots**
```
kit@DESKTOP-KTPUE41:~/work/sketches/js/node-sql-parser$ node demo.js

/home/kit/work/sketches/js/node-sql-parser/node_modules/node-sql-parser/build/mysql.js:20514
      throw peg$buildStructuredError(
      ^
peg$SyntaxError: Expected "!=", "#", "%", "&&", "(", "*", "+", "-", "--", "->", "->>", ".", "/", "/*", ";", "<", "<=", "<>", "=", ">", ">=", "BETWEEN", "FOR", "GROUP", "HAVING", "IN", "IS", "LIKE", "LIMIT", "NOT", "ORDER", "UNION", "||", [ \t\n\r], or end of input but "a" found.
    at peg$buildStructuredError (/home/kit/work/sketches/js/node-sql-parser/node_modules/node-sql-parser/build/mysql.js:2037:14)
    at Object.peg$parse [as mysql] (/home/kit/work/sketches/js/node-sql-parser/node_modules/node-sql-parser/build/mysql.js:20514:13)
    at Parser.parse (/home/kit/work/sketches/js/node-sql-parser/node_modules/node-sql-parser/lib/parser.js:51:52)
    at Parser.astify (/home/kit/work/sketches/js/node-sql-parser/node_modules/node-sql-parser/lib/parser.js:36:28)
    at Object.<anonymous> (/home/kit/work/sketches/js/node-sql-parser/demo.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  expected: [
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '.', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '(', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '.', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '->>', ignoreCase: false },
    { type: 'literal', text: '->', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '.', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '||', ignoreCase: false },
    { type: 'literal', text: '&&', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '.', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '(', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '.', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '->>', ignoreCase: false },
    { type: 'literal', text: '->', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '.', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '*', ignoreCase: false },
    { type: 'literal', text: '/', ignoreCase: false },
    { type: 'literal', text: '%', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '+', ignoreCase: false },
    { type: 'literal', text: '-', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: '>=', ignoreCase: false },
    { type: 'literal', text: '>', ignoreCase: false },
    { type: 'literal', text: '<=', ignoreCase: false },
    { type: 'literal', text: '<>', ignoreCase: false },
    { type: 'literal', text: '<', ignoreCase: false },
    { type: 'literal', text: '=', ignoreCase: false },
    { type: 'literal', text: '!=', ignoreCase: false },
    { type: 'literal', text: 'NOT', ignoreCase: true },
    { type: 'literal', text: 'IN', ignoreCase: true },
    { type: 'literal', text: 'NOT', ignoreCase: true },
    { type: 'literal', text: 'IN', ignoreCase: true },
    { type: 'literal', text: 'NOT', ignoreCase: true },
    { type: 'literal', text: 'BETWEEN', ignoreCase: true },
    { type: 'literal', text: 'IS', ignoreCase: true },
    { type: 'literal', text: 'IS', ignoreCase: true },
    { type: 'literal', text: 'NOT', ignoreCase: true },
    { type: 'literal', text: 'LIKE', ignoreCase: true },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    ... 186 more items
  ],
  found: 'a',
  location: {
    start: { offset: 33, line: 1, column: 34 },
    end: { offset: 34, line: 1, column: 35 }
  }
}
```
**Additional Information**
"select id from foo where deleted" parses successfully, as does "select id from foo where not deleted".

**Comment by taozhi8833998** [comment]
@kpeters-cbsi got it.

**Comment by taozhi8833998** [comment]
@kpeters-cbsi `2.2.7` has been released to fix the issue, give it a shot.

**Comment by kpeters-cbsi** [comment]
That worked! I'll be sure to let you know the next time my project's SQL
runs up against the boundaries of your parser. :)

**Comment by taozhi8833998** [comment]
@kpeters-cbsi ok, keep waiting, thanks. I will close the issue.
