### ISSUE TITLE
Astify does not recognize escaped single quotes in single-quoted string

### ISSUE THREAD

**Issue by estar** [taozhi8833998/node-sql-parser#415]
**Describe the bug**
Restating #314. Standard SQL allows embedding of single quotes in a string like this:
```sql
SELECT '''To be, or not'', it starts.';
```
Demo: http://sqlfiddle.com/#!9/9eecb/159907/0

astify() throws a SyntaxError.

**Database Engine**
I’m interested particularly in PostgreSQL, which supports the syntax given above. Per https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS:
> To include a single-quote character within a string constant, write two adjacent single quotes, e.g., `'Dianne''s horse'`.

**To Reproduce**
On commit ab0ee68c53f3a5d77f1f059df8ab80b3c34c20d6, using node.js 12.14.0, test case:
```js
it('should parse escaped single quotes in a single-quoted string', () => {
  const ast = parser.astify("SELECT '''To be, or not'', it starts.' AS x;");
  expect(ast.columns).to.be.eql([
    {
      "expr": {
        "type": "string",
        "value": "'To be, or not', it starts."
      },
      "as": "x"
    }
  ]);
});
```

**Expected behavior**
astify() yields AST in the second line.

**Screenshots**
Test output:
```
  1) select
       should parse escaped single quotes in a single-quoted string:
     SyntaxError: Expected "#", ",", "--", "/*", ";", "FOR", "FROM", "GROUP", "HAVING", "LIMIT", "ORDER", "UNION", "WHERE", [ \t\n\r], or end of input but "'" found.
      at peg$buildStructuredError (pegjs/mysql.pegjs:2040:1)
      at Object.peg$parse [as mysql] (pegjs/mysql.pegjs:20597:1)
      at Parser.parse (src/parser.js:20:35)
      at Parser.astify (src/parser.js:7:26)
      at Context.<anonymous> (test/select.spec.js:12:24)
      at processImmediate (internal/timers.js:439:21)
```

**Additional context**
(None.)

**Comment by tbantle22** [comment]
I have also run into this issue with escaped single quotes with MySQL
