### ISSUE TITLE
PosgresSQL DISTINCT inside Aggregation function parse failure

### ISSUE THREAD

**Issue by Samlinxia** [taozhi8833998/node-sql-parser#432]
**Describe the bug**
As title. `ARRAY_AGG(DISTINCT columnName)` yields parsing error

**Database Engine**
PostgreSQL.

**To Reproduce**
The SQL
```
SELECT shipmentId, ARRAY_AGG(DISTINCT name) AS shipmentStopIDs FROM table GROUP BY shipmentId
```
Error stacktrace:
```
    SyntaxError: Expected [A-Za-z0-9_\-] or [A-Za-z0-9_] but " " found.

      at Co (../../taozhi/learning/node-sql-parser/pegjs/postgresql.pegjs:2935:3)
      at Object.parse [as postgresql] (node_modules/node-sql-parser/index.js:1:589892)
      at r.value (node_modules/node-sql-parser/index.js:1:739569)
```

**Expected behavior**
Should be a valid SQL

**Additional context**
Thanks for the help!

**Comment by taozhi8833998** [comment]
@Samlinxia fixed in the next version.
