### ISSUE TITLE
MySQL: Combining grouped expressions with un-grouped within the where_clause fails

### ISSUE THREAD

**Issue by hranum** [taozhi8833998/node-sql-parser#494]
**Describe the bug**
The following queries yields the same results, but the latter one is resulting in a parsing error.

```bash
SyntaxError: Expected "#", "%", "*", "+", "-", "--", "/", "/*", or [ \t\n\r] but "A" found.
at peg$buildStructuredError (pegjs/mysql.pegjs:2068:1)
at Object.peg$parse [as mysql] (pegjs/mysql.pegjs:20851:1)
at Parser.parse (src/parser.js:20:35)
at Parser.astify (src/parser.js:7:26)
```

Works:
```sql
select SOME_COLUMN from TABLE_NAME where OTHER_ID_COLUMN > 3 AND (ID_COLUMN = 1 OR ID_COLUMN > 2)
```

Does not work:
```sql
select SOME_COLUMN from TABLE_NAME where (ID_COLUMN = 1 OR ID_COLUMN > 2) AND OTHER_ID_COLUMN > 3
```

Additionally, having multiple grouped expressions, like the following query, will not work either:

```sql
select SOME_COLUMN from TABLE_NAME where OTHER_ID_COLUMN > 3 AND (ID_COLUMN = 1 OR ID_COLUMN > 2) AND (THIRD_ID_COLUMN = 10 OR THIRD_ID_COLUMN > 20);
```

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed
Described above
-the node-sql-parser version
3.1.0
-the node version 
12.16.3

**Expected behavior**
I've attached tests that should not fail to give expected behavior of parsing these correctly.
```js
  it('should support grouped expressions where the group comes before the un-grouped expression', () => {
    const ast = parser.astify('select SOME_COLUMN from TABLE_NAME where (ID_COLUMN = 1 OR ID_COLUMN > 2) AND `OTHER_ID_COLUMN` > 3 for update');
    expect(parser.sqlify(ast)).to.eql('SELECT `SOME_COLUMN` FROM `TABLE_NAME` WHERE (`ID_COLUMN` = 1 OR `ID_COLUMN` > 2) AND `OTHER_ID_COLUMN` > 3 FOR UPDATE');
  });

  it('should support multiple grouped expressions', () => {
    const ast = parser.astify('select SOME_COLUMN from TABLE_NAME where (ID_COLUMN = 1 OR ID_COLUMN > 2) AND (ANOTHER_ID_COLUMN = 10 OR ANOTHER_ID_COLUMN > 20) AND `OTHER_ID_COLUMN` > 3 for update');
    expect(parser.sqlify(ast)).to.eql('SELECT `SOME_COLUMN` FROM `TABLE_NAME` WHERE (`ID_COLUMN` = 1 OR `ID_COLUMN` > 2) AND (`ANOTHER_ID_COLUMN` = 10 OR `ANOTHER_ID_COLUMN` > 20) AND `OTHER_ID_COLUMN` > 3 FOR UPDATE');
  });

  it('should support multiple grouped expressions in any order', () => {
    const ast = parser.astify('select SOME_COLUMN from TABLE_NAME where (ID_COLUMN = 1 OR ID_COLUMN > 2) AND `OTHER_ID_COLUMN` > 3 AND (ANOTHER_ID_COLUMN = 10 OR ANOTHER_ID_COLUMN > 20) for update');
    expect(parser.sqlify(ast)).to.eql('SELECT `SOME_COLUMN` FROM `TABLE_NAME` WHERE (`ID_COLUMN` = 1 OR `ID_COLUMN` > 2) AND `OTHER_ID_COLUMN` > 3 AND (`ANOTHER_ID_COLUMN` = 10 OR `ANOTHER_ID_COLUMN` > 20) FOR UPDATE');
  });
```

**Comment by taozhi8833998** [comment]
@hranum it has been fixed in the latest version 3.3.0, try it.
