### ISSUE TITLE
Semi colon breaking DROP and UPDATE queries.

### ISSUE THREAD

**Issue by Quinncuatro** [taozhi8833998/node-sql-parser#50]
```
const { Parser } = require('node-sql-parser');
const parser = new Parser();

const ast = parser.astify("TRUNCATE TABLE whatever;")

console.log("-------------------");
console.log(ast[0].type);
```

is outputting

```
/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/build/pegjs-parser.js:13185
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "--", ".", "/*", [ \t\n\r], [A-Za-z0-9_], or end of input but ";" found.
    at peg$buildStructuredError (/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/build/pegjs-parser.js:1203:12)
    at peg$parse (/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/build/pegjs-parser.js:13185:11)
    at Parser.parse (/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/lib/parser.js:17:12)
    at Parser.astify (/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/lib/parser.js:8:26)
    at Object.<anonymous> (/Users/hquinn/dev/GoBStopper/incremental/test/test.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by taozhi8833998** [comment]
it supported drop and truncate cmd with semicolon suffix in SQL, and the corresponding commit is 56c3f077d25eb4d8f7697ab4cfc49b727847560f. But it looks like semicolon didn't break **UPDATE** queries, you could show me the example. I will publish new version **1.3.3** when another issue been sovled

**Comment by Quinncuatro** [comment]
Sorry, meant TRUNCATE instead of UPDATE.

**Comment by Quinncuatro** [comment]
```
const { Parser } = require('node-sql-parser');
const parser = new Parser();

const ast4 = parser.astify("TRUNCATE TABLE whatever;")

console.log(ast4.type);
```

outputs

```
/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/build/pegjs-parser.js:13185
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "--", ".", "/*", [ \t\n\r], [A-Za-z0-9_], or end of input but ";" found.
    at peg$buildStructuredError (/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/build/pegjs-parser.js:1203:12)
    at peg$parse (/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/build/pegjs-parser.js:13185:11)
    at Parser.parse (/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/lib/parser.js:17:12)
    at Parser.astify (/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/lib/parser.js:8:26)
    at Object.<anonymous> (/Users/hquinn/dev/GoBStopper/incremental/test/test.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by taozhi8833998** [comment]
upgrade `node-sql-parser` to version **1.3.3**

**Comment by Quinncuatro** [comment]
Word. Will do later this morning and I'll report back with the results!

**Comment by Quinncuatro** [comment]
Looks like it's good. Thanks for being so on the ball with issues!

Sure I can't send you $5 for coffee or whatever?

**Comment by taozhi8833998** [comment]
add coffee pay in `readme` by PayPal, Alipay, and Wechat. Thanks for your kindness
