### ISSUE TITLE
Syntax error on: SELECT a, b, c FROM tb WHERE a like 'test1' OR b = 'test2'

### ISSUE THREAD

**Issue by labs20** [taozhi8833998/node-sql-parser#510]
**Describe the bug**
Getting a syntax error from this simple query: 
`SELECT a, b, c FROM tb WHERE a like 'test1' OR b = 'test2'`

```
u [SyntaxError]: Expected "!=", "#", "%", "*", "+", "-", "--", "/", "/*", ";", "<", "<=", "<>", "=", ">", ">=", "BETWEEN", "GROUP", "HAVING", "IN", "IS", "LIKE", "LIMIT", "NOT", "ORDER", "UNION", [ \t\n\r], or end of input but "O" found.
    at co (/Users/labs/node_modules/node-sql-parser/index.js:1:600442)
    at Object.parse [as transactsql] (/Users/labs/node_modules/node-sql-parser/index.js:1:711123)
    at r.value (/Users/labs/node_modules/node-sql-parser/index.js:1:861368)
    at r.value (/Users/labs/node_modules/node-sql-parser/index.js:1:861048)
    at Object.<anonymous> (/Users/labs/WebstormProjects/untitled/test.js:9:11)
[38;2;0;0;127m
Process finished with exit code 130 (interrupted by signal 2: SIGINT)

```
**Database Engine**
TransactSQL 

SQL being executed like this:
```
const { Parser }= require('node-sql-parser')
    , sqlParser = new Parser()
;
sqlParser.astify("SELECT a, b, c FROM tb WHERE a like 'test1' OR b = 'test2'");
```

and this:
```
const { Parser }= require('node-sql-parser')
    , sqlParser = new Parser()
;
sqlParser.astify("SELECT a, b, c FROM tb WHERE a like 'test1' OR b = 'test2'", {
     database: 'TransactSQL'
});
```
On a clean js file with no other code beyond this test.

**To Reproduce**
```
const { Parser }= require('node-sql-parser')
    , sqlParser = new Parser()
    , opt = {
          database: 'TransactSQL' // MySQL is the default database
      }
;
sqlParser.astify("SELECT a, b, c FROM tb WHERE a like 'test1' OR b = 'test2'", opt);

```
node-sql-parser version: 3.1.0
node version: 14.9.0

**Expected behavior**
This SQL should not raise an syntax error

**Comment by wo997** [comment]
Today I have spotted the same issue, is this one in progress?

**Comment by Cycade** [comment]
Same issue. Is there any plan to fix it?

**Comment by Val-istar-Guo** [comment]
Same issue...

**Comment by wo997** [comment]
Not sure if anyone wanted more details, but from my observations the parser knows what the "like" keyword means (I checked the parsed AST) but it fails whenever something is after, like "OR b = 'test2'" mentioned above.

**Comment by taozhi8833998** [comment]
@labs20 @wo997 @Val-istar-Guo @Cycade  I am fixing it now.

**Comment by taozhi8833998** [comment]
@labs20 it has been fixed. I will publish a new version this week.
