### ISSUE TITLE
Having an issue with periods in CALL statements.

### ISSUE THREAD

**Issue by Quinncuatro** [taozhi8833998/node-sql-parser#52]
```
const { Parser } = require('node-sql-parser');
const parser = new Parser();

const ast = parser.astify("CALL `db_name`.`backup-trigger`('other_db_name', 'table_name', 'param1', 'param2', 'QUERY TO RUN;")

console.log("-------------------");
console.log(ast);
console.log("-------------------");
```

is outputting

```
MAC-L028-0001:test hquinn$ node test2.js 

/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/build/pegjs-parser.js:13293
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "(", "--", "/*", [ \t\n\r], or end of input but "." found.
    at peg$buildStructuredError (/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/build/pegjs-parser.js:1218:12)
    at peg$parse (/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/build/pegjs-parser.js:13293:11)
    at Parser.parse (/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/lib/parser.js:17:12)
    at Parser.astify (/Users/hquinn/dev/GoBStopper/incremental/test/node_modules/node-sql-parser/lib/parser.js:8:26)
    at Object.<anonymous> (/Users/hquinn/dev/GoBStopper/incremental/test/test2.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by taozhi8833998** [comment]
added in 444cab17ad1ef3845c59d67b59b514209ad152f5. BTW, whethe an right parentheses missed in ur `call` statment??

```
const ast = parser.astify("CALL `db_name`.`backup-trigger`('other_db_name', 'table_name', 'param1', 'param2', 'QUERY TO RUN);")
```

**Comment by taozhi8833998** [comment]
I will publish it in `1.3.4` version later

**Comment by Quinncuatro** [comment]
Seems to work fine now! 👍🏻
