### ISSUE TITLE
Add support for DROP and TRUNCATE when astify-ing a file.

### ISSUE THREAD

**Issue by Quinncuatro** [taozhi8833998/node-sql-parser#55]
```
var fs = require('fs');
const removeEmptyLines = require("remove-blank-lines");

const { Parser } = require('node-sql-parser');
const parser = new Parser();

let data = ""
let tablesToBackUp = []
let tablesThatAreBackedUp = []

function sanitizeSQL() {
  data = fs.readFileSync('testfile.sql', 'utf-8');
  data = data.replace(/^USE.*\n?/m, '');
  data = data.replace(/^use.*\n?/m, '');
  data = data.replace(/^#.*\n?/m, '');
  data = data.replace(/^--.*\n?/m, '');
  data = data.replace(/\/\/*[\s\S]*?\*\//gm, "");
  // data = data.replace(/;/g, "");
  data = removeEmptyLines(data);
  console.log(data);
  console.log("-------");

  astThatShit(data);
}

function astThatShit(data) {
  var ast = parser.astify(data)
  console.log(ast);
  console.log("-------");

  checkTables(ast)
}

function checkTables(ast) {
  for(var i = 0; i < ast.length; i++) {
    switch(ast[i].type) {
      case "update":
      case "insert":
      case "truncate":
      case "drop":
        tablesToBackUp.push(ast[i].table);
        break;
      case "delete":
        tablesToBackUp.push(ast[i].from[0].table);
      default:
        // code block
        break;
    }
  }

  console.log("Tables that need to be backed up:");
  console.log(tablesToBackUp);
  console.log("-------");
}

sanitizeSQL();
```

when using a `testfile.sql` file that includes lines like `DROP TABLE table` or `TRUNCATE TABLE whatever` outputs:

```
/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:13293
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "$", "(", "--", "/*", ";", "@", "DELETE", "INSERT", "REPLACE", "SELECT", "UPDATE", "WITH", "return", [ \t\n\r], or end of input but "D" found.
    at peg$buildStructuredError (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:1218:12)
    at peg$parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:13293:11)
    at Parser.parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:17:12)
    at Parser.astify (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:8:26)
    at astThatShit (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/arrayChecker.js:27:20)
    at sanitizeSQL (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/arrayChecker.js:23:3)
    at Object.<anonymous> (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/arrayChecker.js:56:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by taozhi8833998** [comment]
could you show me some SQLs in `testfile.sql`, so I can reappear what you met

**Comment by Quinncuatro** [comment]
Seems to work fine now! 👍🏻
