### ISSUE TITLE
Add support for table aliases

### ISSUE THREAD

**Issue by Quinncuatro** [taozhi8833998/node-sql-parser#56]
```
UPDATE tbl_AlphaBetaOmega abo
	JOIN tbl_TreeBark tb ON abo.id = tb.id 
WHERE cm.secondaryID in (1, 2, 3, 4, 5) AND cmi.otherRow = "whatever";
```

outputs

```
/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:13344
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "--", ".", "/*", "SET", or [ \t\n\r] but "a" found.
    at peg$buildStructuredError (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:1232:12)
    at peg$parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:13344:11)
    at Parser.parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:17:12)
    at Parser.astify (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:8:26)
    at astThatShit (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/arrayChecker.js:42:20)
    at sanitizeSQL (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/arrayChecker.js:38:3)
    at Object.<anonymous> (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/arrayChecker.js:96:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by taozhi8833998** [comment]
supported in 0a77068b69d744e53bc13450bdc111d8f0cd8149, But I removed the `tables` in `delete` SQL using `table` instead !!! This is an break change, you need change   when upgrade version to `1.4.0`. Sorry for that. BTW, the SQL 
```SQL
UPDATE tbl_AlphaBetaOmega abo
	JOIN tbl_TreeBark tb ON abo.id = tb.id 
WHERE cm.secondaryID in (1, 2, 3, 4, 5) AND cmi.otherRow = "whatever";
```
missed  `SET` clause that you should add

**Comment by Quinncuatro** [comment]
Word! 

While we're on `SET`, could you add `SET` as a first class query?

`
SET @oldvalue = 12345;
SET @newvalue = '';
`

outputs

`
/usr/src/app/node_modules/node-sql-parser/build/pegjs-parser.js:13344
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "$", "(", "--", "/*", ";", "@", "CALL", "DELETE", "DROP", "INSERT", "RENAME", "REPLACE", "SELECT", "TRUNCATE", "UPDATE", "USE", "WITH", "return", [ \t\n\r], or end of input but "S" found.
    at peg$buildStructuredError (/usr/src/app/node_modules/node-sql-parser/build/pegjs-parser.js:1232:12)
    at peg$parse (/usr/src/app/node_modules/node-sql-parser/build/pegjs-parser.js:13344:11)
    at Parser.parse (/usr/src/app/node_modules/node-sql-parser/lib/parser.js:17:12)
    at Parser.astify (/usr/src/app/node_modules/node-sql-parser/lib/parser.js:8:26)
    at astThatShit (/usr/src/app/arrayChecker.js:37:20)
    at sanitizeSQL (/usr/src/app/arrayChecker.js:33:3)
    at Object.<anonymous> (/usr/src/app/arrayChecker.js:102:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
`

**Comment by taozhi8833998** [comment]
it looks like you are defining some variables, and later you would use @oldvalue instead of 12345. OK, I will support that

**Comment by Quinncuatro** [comment]
Thank you so much!

**Comment by taozhi8833998** [comment]
`set` command has been supported in `1.4.1-beta` version since `alter` has lots of grammar, It will take some time to finish support that all.

**Comment by Quinncuatro** [comment]
Take your time on it. I'm fleshing out some other parts of this application. I think I have a demo for the company I'm working for on Monday, but I can use some SQL files for the demo that don't include `ALTER`.

**Comment by taozhi8833998** [comment]
ok，I will keep working on this modular
