### ISSUE TITLE
Add ALTER support

### ISSUE THREAD

**Issue by Quinncuatro** [taozhi8833998/node-sql-parser#57]
```
ALTER TABLE tbl_whatever ADD COLUMN dateOfThing date; 
```

outputs

```
/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:13344
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "$", "(", "--", "/*", ";", "@", "CALL", "DELETE", "DROP", "INSERT", "RENAME", "REPLACE", "SELECT", "TRUNCATE", "UPDATE", "USE", "WITH", "return", [ \t\n\r], or end of input but "A" found.
    at peg$buildStructuredError (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:1232:12)
    at peg$parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:13344:11)
    at Parser.parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:17:12)
    at Parser.astify (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:8:26)
    at astThatShit (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/arrayChecker.js:42:20)
    at sanitizeSQL (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/arrayChecker.js:38:3)
    at Object.<anonymous> (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/arrayChecker.js:96:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by taozhi8833998** [comment]
developing... coming soon

**Comment by Quinncuatro** [comment]
You. Are. The. Man.

Check your PayPal later!

**Comment by taozhi8833998** [comment]
`1.4.1-beta` version support `alter` to parse add the column, drop the column. Alter has lots of grammar, It will take some time to finish support that all. When I finished that all, I will publish an offical version instead of beta. if you have any emergency alter grammar please let me know!!

**Comment by taozhi8833998** [comment]
you could try `1.4.1-beta` version for partial supported `alter` grammar now

**Comment by Quinncuatro** [comment]
Will do!

**Comment by taozhi8833998** [comment]
support `alter table` on `index`

**Comment by Quinncuatro** [comment]
Should this be closed out?

**Comment by taozhi8833998** [comment]
yup, you can close it if the parser does parse your SQL with alter grammar.
