### ISSUE TITLE
MySQL parser not recognizing BIT type

### ISSUE THREAD

**Issue by tbantle22** [taozhi8833998/node-sql-parser#594]
**Describe the bug**

This query `ALTER TABLE newtable ADD newcol BIT(1)` returns this error (same for a CREATE TABLE statement that includes `BIT(1)`):

```
"SyntaxError: Expected "#", "--", "->", "->>", ".", "/*", "BIGINT", "CHAR", "DATE", "DATETIME", "DECIMAL", "DOUBLE", "FLOAT", "INT", "INTEGER", "JSON", "LONGTEXT", "MEDIUMTEXT", "NUMERIC", "SMALLINT", "TEXT", "TIME", "TIMESTAMP", "TINYINT", "TINYTEXT", "VARCHAR", or [ \t\n\r] but "B" found.
    at https://www.dolthub.com/_next/static/chunks/7a960922.ce51224d7ca786ce339e.js:1:366592
    at Object.parse [as mysql] (https://www.dolthub.com/_next/static/chunks/7a960922.ce51224d7ca786ce339e.js:1:366625)
    at r.value (https://www.dolthub.com/_next/static/chunks/7a960922.ce51224d7ca786ce339e.js:1:849101)
    at r.value (https://www.dolthub.com/_next/static/chunks/7a960922.ce51224d7ca786ce339e.js:1:848781)
    at l (https://www.dolthub.com/_next/static/chunks/pages/repositories/%5BownerName%5D/%5BrepoName%5D/workspaces/%5BworkspaceName%5D-0817c7b15414f5a50ee7.js:1:716765)
    at d (https://www.dolthub.com/_next/static/chunks/pages/repositories/%5BownerName%5D/%5BrepoName%5D/workspaces/%5BworkspaceName%5D-0817c7b15414f5a50ee7.js:1:716922)
    at me (https://www.dolthub.com/_next/static/chunks/pages/repositories/%5BownerName%5D/%5BrepoName%5D/workspaces/%5BworkspaceName%5D-0817c7b15414f5a50ee7.js:1:938932)
    at Pe (https://www.dolthub.com/_next/static/chunks/pages/repositories/%5BownerName%5D/%5BrepoName%5D/workspaces/%5BworkspaceName%5D-0817c7b15414f5a50ee7.js:1:940215)
    at ro (https://www.dolthub.com/_next/static/chunks/framework.e6a1ac6d0d5ad9183bab.js:1:72372)
    at jo (https://www.dolthub.com/_next/static/chunks/framework.e6a1ac6d0d5ad9183bab.js:1:81939)"
```

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed "ALTER TABLE newtable ADD newcol BIT(1)"
-the node-sql-parser version 3.1.0
-the node version v12.19.0

**Expected behavior**
A query that include BIT(1) should successfully parse

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@tbantle22 it has been supported, I will publish new version this week.

**Comment by tbantle22** [comment]
Appreciate that, thank you!
