### ISSUE TITLE
Add backtick support for TRUNCATE (and other query types).

### ISSUE THREAD

**Issue by Quinncuatro** [taozhi8833998/node-sql-parser#62]
`
TRUNCATE `db_name`.`table_name`;
`

outputs

`
/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:13376
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "--", "/*", "TABLE", or [ \t\n\r] but "`" found.
    at peg$buildStructuredError (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:1241:12)
    at peg$parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:13376:11)
    at Parser.parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:17:12)
    at Parser.astify (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:8:26)
    at astThatShit (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/code/localArrayChecker.js:37:20)
    at sanitizeSQL (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/code/localArrayChecker.js:33:3)
    at Object.<anonymous> (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/code/localArrayChecker.js:106:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
`

**Comment by taozhi8833998** [comment]
you could use `TRUNCATE TABLE db_name.table_name;` currently, The `TABLE`  keyword is required now, I will change it to optional later

**Comment by Quinncuatro** [comment]
In a perfect world, the folks writing all of the SQL I'm parsing would be following a strict standard. Unfortunately that's not the world I live in, haha. 🙃

**Comment by taozhi8833998** [comment]
add in 968fcb7b3a986d33e47bb4d8f5da2b3c15769d6f

**Comment by taozhi8833998** [comment]
> In a perfect world, the folks writing all of the SQL I'm parsing would be following a strict standard. Unfortunately that's not the world I live in, haha. 🙃

haha, try `1.4.1` version
