### ISSUE TITLE
Add ENGINE / AUTO_INCREMENT / etc... support

### ISSUE THREAD

**Issue by Quinncuatro** [taozhi8833998/node-sql-parser#63]
`
CREATE TABLE `db_name`.`table_name` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
`

outputs

`
/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:13376
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "--", ".", "/*", ";", [ \t\n\r], or end of input but "E" found.
    at peg$buildStructuredError (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:1241:12)
    at peg$parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:13376:11)
    at Parser.parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:17:12)
    at Parser.astify (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:8:26)
    at astThatShit (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/code/localArrayChecker.js:37:20)
    at sanitizeSQL (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/code/localArrayChecker.js:33:3)
    at Object.<anonymous> (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/code/localArrayChecker.js:106:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
`

**Comment by Quinncuatro** [comment]
Sorry, was working on other parts of this project. I'll start submitting more issues as I find them.

Any update on this, though? ^^

**Comment by taozhi8833998** [comment]
working on it, I will publish this feature later

**Comment by taozhi8833998** [comment]
already supported `create table syntax`, I will publish new version after all test cases passed

**Comment by taozhi8833998** [comment]
@Quinncuatro try version 1.5.0
