### ISSUE TITLE
Add `SET whatever = "data"` support

### ISSUE THREAD

**Issue by Quinncuatro** [taozhi8833998/node-sql-parser#64]
`
UPDATE `tbl_name` SET `Label` = 'LABEL_NAME', `Column_Name` = 'column-data' WHERE `id` = '15';
`

outputs

`
/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:13376
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "--", ".", "/*", or [ \t\n\r] but "=" found.
    at peg$buildStructuredError (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:1241:12)
    at peg$parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:13376:11)
    at Parser.parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:17:12)
    at Parser.astify (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:8:26)
    at astThatShit (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/code/localArrayChecker.js:37:20)
    at sanitizeSQL (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/code/localArrayChecker.js:33:3)
    at Object.<anonymous> (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/code/localArrayChecker.js:116:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
`

**Comment by taozhi8833998** [comment]
it supported before, and the SQL that you pasted been parsed successfully!!! If I am wrong, correct me, and reopen this issue

**Comment by Quinncuatro** [comment]
UPDATE `tbl_name` SET `Label` = 'LABEL_NAME', `Column_Name` = 'column-data' WHERE `id` = '15'

**Comment by Quinncuatro** [comment]
Try this version. The original comment hid my backticks.

**Comment by Quinncuatro** [comment]
Was not working on 1.4.0

**Comment by taozhi8833998** [comment]
Sorry for that, try `1.4.1` version
