### ISSUE TITLE
Reall unsure what's happening here. Seems like it doesn't like a WHERE on an UPDATE.

### ISSUE THREAD

**Issue by Quinncuatro** [taozhi8833998/node-sql-parser#65]
```
UPDATE tbl_alphabeta ab 
	JOIN tbl_yankeezulu yz ON ab.id = yz.thing_id 
SET  yz.attr_89 = @newinsert 
WHERE ab.id in (1, 2, 3, 4, 5) AND yz.attr_89 = @oldinsert;
```

outputs

```
/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:14278
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "!=", "#", "%", "*", "+", ",", "-", "--", "/", "/*", "<", "<=", "<>", "=", ">", ">=", "AND", "FULL", "INNER", "JOIN", "LEFT", "OR", "RIGHT", "SET", or [ \t\n\r] but "W" found.
    at peg$buildStructuredError (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:1333:12)
    at peg$parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/build/pegjs-parser.js:14278:11)
    at Parser.parse (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:17:12)
    at Parser.astify (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/node_modules/node-sql-parser/lib/parser.js:8:26)
    at astThatStuff (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/code/localArrayChecker.js:37:20)
    at sanitizeSQL (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/code/localArrayChecker.js:33:3)
    at Object.<anonymous> (/Users/hquinn/dev/GoBStopper/incremental/arrayChecker/code/localArrayChecker.js:112:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by Quinncuatro** [comment]
Nevvvvvvvermind. Had my `SET @oldinsert = xxx` and `SET @newinsert = yyy` commented out from an older version of node-sql-parser. Uncommented and everything works perfect!
