### ISSUE TITLE
mysql create table query parsing error

### ISSUE THREAD

**Issue by myyrakle** [taozhi8833998/node-sql-parser#663]
**Describe the bug**
If "auto_increment" and "key clause" exist in mysql's create table query, it is not read properly and an error is thrown.

```
u [SyntaxError]: Expected "#", ")", ",", "--", "/*", "COLLATE", "COLUMN_FORMAT", "COMMENT", "KEY", "PRIMARY", "REFERENCES", "STORAGE", "UNIQUE", or [ \t\n\r] but "N" found.
    at $u (C:\Users\sssan\Code\Node\eojuk\node_modules\node-sql-parser\index.js:1:294222)
    at Object.parse [as mysql] (C:\Users\sssan\Code\Node\eojuk\node_modules\node-sql-parser\index.js:1:400566)
    at r.value (C:\Users\sssan\Code\Node\eojuk\node_modules\node-sql-parser\index.js:1:927675)
    at r.value (C:\Users\sssan\Code\Node\eojuk\node_modules\node-sql-parser\index.js:1:927355)
    at Object.<anonymous> (C:\Users\sssan\Code\Node\eojuk\src\main.js:31:25)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
...
```

**Database Engine**
MySQL

**To Reproduce**
The query below will cause an error while parsing.
```
const mysqlQuery = `CREATE TABLE test (
    id int(11) AUTO_INCREMENT NOT NULL,
    name varchar(100) NOT NULL,
    description longtext ,
    image_url varchar(200)  DEFAULT NULL,
    PRIMARY KEY (id),
    KEY brand_info_name_index(name)
  ) ENGINE=InnoDB AUTO_INCREMENT=133 DEFAULT CHARSET=utf8 COLLATE=utf8_bin`;

console.log(mysqlParser.astify(mysqlQuery));
```

However, if I remove the auto_increment and key clauses in question from that code, it works normally.
```
const mysqlQuery = `CREATE TABLE test (
    id int(11) NOT NULL,
    name varchar(100) NOT NULL,
    description longtext ,
    image_url varchar(200)  DEFAULT NULL,
    PRIMARY KEY (id)
  ) ENGINE=InnoDB AUTO_INCREMENT=133 DEFAULT CHARSET=utf8 COLLATE=utf8_bin`;

console.log(mysqlParser.astify(mysqlQuery));
```
In the case of auto_increment, moving to the right of "not null" works normally.

**Expected behavior**
I think the "key clause" should be recognized as valid and readable no matter where the "auto_increment" is.

**Screenshots**
none

**Additional context**
none

**Comment by taozhi8833998** [comment]
@myyrakle The [create table syntax](https://dev.mysql.com/doc/refman/8.0/en/create-table.html) shows `NOT NULL` keyword should put before the `AUTO_INCREMENT` keyword, the SQL below is valid: 

```sql
CREATE TABLE test (
    id int(11) NOT NULL AUTO_INCREMENT,
    name varchar(100) NOT NULL,
    description longtext ,
    image_url varchar(200)  DEFAULT NULL,
    PRIMARY KEY (id),
    KEY brand_info_name_index(name)
  ) ENGINE=InnoDB AUTO_INCREMENT=133 DEFAULT CHARSET=utf8 COLLATE=utf8_bin
```
