### ISSUE TITLE
SQLite: `||` operator support

### ISSUE THREAD

**Issue by goliatone** [taozhi8833998/node-sql-parser#719]
**Describe the bug**
SQLite parser does not support `||` operator

**Database Engine**
SQLite.

**To Reproduce**
```sql
SELECT * 
FROM
    pets 
    LEFT JOIN(
        SELECT * FROM user
        WHERE user.name = "pepe" || "rone"
    ) u ON pets.owner = u.id
GROUP BY pets.id;
```
- the node-sql-parser version: 3.6.5
- the node version: v16.5.0

**Expected behavior**
Being able to parse the query

**Additional context**
Stack trace

```
[SyntaxError]: Expected "!=", "#", "%", ")", "*", "+", "-", "--", "/", "/*", "<", "<=", "<>", "=", ">", ">=", "AND", "COLLATE", "FOR", "GROUP", "HAVING", "LIMIT", "OR", "ORDER", "UNION", or [ \t\n\r] but "|" found.
    at Pu (~/node_modules/node-sql-parser/index.js:1:662248)
    at Object.parse [as sqlite] (~/node_modules/node-sql-parser/index.js:1:768108)
    at r.value (~/node_modules/node-sql-parser/index.js:1:1050402)
    at Object.<anonymous> (~/sql-parse.js:22:12)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by taozhi8833998** [comment]
@goliatone it has been supported in the new version `3.6.9`, try it.
