### ISSUE TITLE
BigQuery: parser breaks on "accessing array elements" 

### ISSUE THREAD

**Issue by joffreyvillard** [taozhi8833998/node-sql-parser#727]
**Describe the bug**

In BigQuery, accessing array elements is performed via `OFFSET()` and `ORDINAL()` functions (see https://cloud.google.com/bigquery/docs/reference/standard-sql/arrays#accessing_array_elements).

The query below (directly coming from the doc linked above) is a perfectly valid BigQuery SQL query (executes well in BigQuery SQL Workspace), but node-sql-parser raises the error below.

```
WITH sequences AS
  (SELECT [0, 1, 1, 2, 3, 5] AS some_numbers
   UNION ALL SELECT [2, 4, 8, 16, 32] AS some_numbers
   UNION ALL SELECT [5, 10] AS some_numbers)
SELECT some_numbers,
       some_numbers[OFFSET(1)] AS offset_1,
       some_numbers[ORDINAL(1)] AS ordinal_1
FROM sequences
```

Error:

```
[SyntaxError]: Expected "!=", "#", "%", "&&", "'", "(", "*", "+", ",", "-", "--", ".", "/", "/*", ";", "<", "<=", "<>", "=", ">", ">=", "AS", "BETWEEN", "EXCEPT", "FOR", "FROM", "GROUP", "HAVING", "IN", "INTERSECT", "IS", "LIKE", "LIMIT", "NOT", "ORDER", "SELECT", "UNION", "WHERE", "WINDOW", "\"", "`", "||", [ \t\n\r], [A-Za-z0-9_:], [A-Za-z0-9_], [A-Za-z_], or end of input but "[" found.
    at peg$buildStructuredError (/Users/taozhi/learning/node-sql-parser/pegjs/bigquery.pegjs:1440:12)
    at Object.typeCase (/Users/taozhi/learning/node-sql-parser/pegjs/bigquery.pegjs:15991:11)
    at r.parse (/Users/taozhi/learning/node-sql-parser/src/parser.js:20:43)
    at r.value (/Users/taozhi/learning/node-sql-parser/src/parser.js:7:26)
    [...]
) {
  expected: [
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    [...]
  ],
  found: '[',
  location: {
    start: { offset: 202, line: 6, column: 20 },
    end: { offset: 203, line: 6, column: 21 }
  }
}
```

**Database Engine**
BigQuery

**To Reproduce**
-the SQL that be parsed: see above
-the node-sql-parser version: 3.6.6
-the node version: 14.15.5

**Expected behavior**
No error, and the appropriate properties being filled up in the AST.

**Screenshots**
-

**Additional context**
-

**Comment by taozhi8833998** [comment]
@joffreyvillard try the new version `3.6.8`

**Comment by joffreyvillard** [comment]
Wow excellent, thanks a lot :rocket: :star_struck:
