### ISSUE TITLE
Parenthesis are not supported inside expressions in CASE WHEN statements

### ISSUE THREAD

**Issue by planetbeing** [taozhi8833998/node-sql-parser#786]
**Describe the bug**
Parenthesis are not supported in CASE WHEN statements.

**Database Engine**
MySQL

**To Reproduce**
Using `node-sql-parser` version 3.8.4.
```
const { Parser } = require("node-sql-parser");
console.log((new Parser()).astify('SELECT CASE WHEN (a - b) = 1 THEN 1 ELSE 0 END FROM t'));
```

**Expected behavior**
This should output the AST for `SELECT CASE WHEN (a - b) = 1 THEN 1 ELSE 0 END FROM t`

**Output**
```
u [SyntaxError]: Expected "#", "--", "/*", "AND", "OR", "THEN", or [ \t\n\r] but "=" found.
    at Qu (/Users/planetbeing/Documents/git/sharding/node_modules/node-sql-parser/index.js:1:298174)
    at Object.parse [as mysql] (/Users/planetbeing/Documents/git/sharding/node_modules/node-sql-parser/index.js:1:411372)
    at r.value (/Users/planetbeing/Documents/git/sharding/node_modules/node-sql-parser/index.js:1:1065757)
    at r.value (/Users/planetbeing/Documents/git/sharding/node_modules/node-sql-parser/index.js:1:1065437)
    at Object.<anonymous> (/Users/planetbeing/Documents/git/sharding/index.js:2:28)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  expected: [
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'AND', ignoreCase: true },
    { type: 'literal', text: 'OR', ignoreCase: true },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'THEN', ignoreCase: true },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'AND', ignoreCase: true },
    { type: 'literal', text: 'OR', ignoreCase: true },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'THEN', ignoreCase: true },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'AND', ignoreCase: true },
    { type: 'literal', text: 'OR', ignoreCase: true },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'THEN', ignoreCase: true },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'AND', ignoreCase: true },
    { type: 'literal', text: 'OR', ignoreCase: true },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'THEN', ignoreCase: true }
  ],
  found: '=',
  location: {
    start: { offset: 25, line: 1, column: 26 },
    end: { offset: 26, line: 1, column: 27 }
  }
}
```

**Additional context**
In `pegjs/mysql.pegjs`, the following is the line for processing `CASE WHEN` statements: https://github.com/taozhi8833998/node-sql-parser/blob/7b0935630ca8bba53a736c54941a9fbc709c5eb7/pegjs/mysql.pegjs#L1731

The type for `condition` ought to be `expr` instead of `or_and_where_expr`, since `or_and_where_expr` causes the parser to assume that if there's a parenthesis in front, then there will be a series of expressions joined by `AND` and/or `OR`, which is not necessarily the case. With `expr`, the case where the expression is a series of expressions joined by `AND` and/or `OR` within parentheses is already handled by `logic_operator_expr` -> `primary`.

**Comment by planetbeing** [comment]
Actually, this bug seems to have been introduced in https://github.com/taozhi8833998/node-sql-parser/commit/cef51717ece376ce48258ce33bd1b1b5d5ffd14a

It might simply be better to change https://github.com/taozhi8833998/node-sql-parser/blob/7b0935630ca8bba53a736c54941a9fbc709c5eb7/pegjs/mysql.pegjs#L1773

to

```
	= head:expr tail:(__ (KW_AND / KW_OR) __ expr)* {
```

And remove `parentheses_or_expr`, which seems redundant as if the whole expression is encapsulated by parenthesis, the regular `expr` rule should handle it as one single expression.
