### ISSUE TITLE
Support BINARY and VARBINARY types

### ISSUE THREAD

**Issue by planetbeing** [taozhi8833998/node-sql-parser#787]
**Describe the bug**
Support BINARY and VARBINARY types

**Database Engine**
MySQL

**To Reproduce**
Using `node-sql-parser` version 3.8.4.
```
const { Parser } = require("node-sql-parser");
console.log(JSON.stringify((new Parser()).astify('SELECT CAST(a AS BINARY) END FROM t'), null, 2));
```

**Expected behavior**
This should output the AST for `SELECT CAST(a AS BINARY) END FROM t`

**Output**
```
u [SyntaxError]: Expected "#", "--", "/*", "BIGINT", "BIT", "CHAR", "DATE", "DATETIME", "DECIMAL", "DOUBLE", "ENUM", "FLOAT", "INT", "INTEGER", "JSON", "LONGTEXT", "MEDIUMTEXT", "NUMERIC", "SIGNED", "SMALLINT", "TEXT", "TIME", "TIMESTAMP", "TINYINT", "TINYTEXT", "UNSIGNED", "VARCHAR", "boolean", or [ \t\n\r] but "B" found.
    at Qu (/Users/planetbeing/Documents/git/sharding/node_modules/node-sql-parser/index.js:1:298174)
    at Object.parse [as mysql] (/Users/planetbeing/Documents/git/sharding/node_modules/node-sql-parser/index.js:1:411372)
    at r.value (/Users/planetbeing/Documents/git/sharding/node_modules/node-sql-parser/index.js:1:1065757)
    at r.value (/Users/planetbeing/Documents/git/sharding/node_modules/node-sql-parser/index.js:1:1065437)
    at Object.<anonymous> (/Users/planetbeing/Documents/git/sharding/index.js:3:43)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  expected: [
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'CHAR', ignoreCase: true },
    { type: 'literal', text: 'VARCHAR', ignoreCase: true },
    { type: 'literal', text: 'CHAR', ignoreCase: true },
    { type: 'literal', text: 'VARCHAR', ignoreCase: true },
    { type: 'literal', text: 'NUMERIC', ignoreCase: true },
    { type: 'literal', text: 'DECIMAL', ignoreCase: true },
    { type: 'literal', text: 'INT', ignoreCase: true },
    { type: 'literal', text: 'INTEGER', ignoreCase: true },
    { type: 'literal', text: 'SMALLINT', ignoreCase: true },
    { type: 'literal', text: 'TINYINT', ignoreCase: true },
    { type: 'literal', text: 'BIGINT', ignoreCase: true },
    { type: 'literal', text: 'FLOAT', ignoreCase: true },
    { type: 'literal', text: 'DOUBLE', ignoreCase: true },
    { type: 'literal', text: 'BIT', ignoreCase: true },
    { type: 'literal', text: 'NUMERIC', ignoreCase: true },
    { type: 'literal', text: 'DECIMAL', ignoreCase: true },
    { type: 'literal', text: 'INT', ignoreCase: true },
    { type: 'literal', text: 'INTEGER', ignoreCase: true },
    { type: 'literal', text: 'SMALLINT', ignoreCase: true },
    { type: 'literal', text: 'TINYINT', ignoreCase: true },
    { type: 'literal', text: 'BIGINT', ignoreCase: true },
    { type: 'literal', text: 'FLOAT', ignoreCase: true },
    { type: 'literal', text: 'DOUBLE', ignoreCase: true },
    { type: 'literal', text: 'NUMERIC', ignoreCase: true },
    { type: 'literal', text: 'DECIMAL', ignoreCase: true },
    { type: 'literal', text: 'INT', ignoreCase: true },
    { type: 'literal', text: 'INTEGER', ignoreCase: true },
    { type: 'literal', text: 'SMALLINT', ignoreCase: true },
    { type: 'literal', text: 'TINYINT', ignoreCase: true },
    { type: 'literal', text: 'BIGINT', ignoreCase: true },
    { type: 'literal', text: 'FLOAT', ignoreCase: true },
    { type: 'literal', text: 'DOUBLE', ignoreCase: true },
    { type: 'literal', text: 'DATE', ignoreCase: true },
    { type: 'literal', text: 'DATETIME', ignoreCase: true },
    { type: 'literal', text: 'TIME', ignoreCase: true },
    { type: 'literal', text: 'TIMESTAMP', ignoreCase: true },
    { type: 'literal', text: 'DATE', ignoreCase: true },
    { type: 'literal', text: 'DATETIME', ignoreCase: true },
    { type: 'literal', text: 'TIME', ignoreCase: true },
    { type: 'literal', text: 'TIMESTAMP', ignoreCase: true },
    { type: 'literal', text: 'JSON', ignoreCase: true },
    { type: 'literal', text: 'TINYTEXT', ignoreCase: true },
    { type: 'literal', text: 'TEXT', ignoreCase: true },
    { type: 'literal', text: 'MEDIUMTEXT', ignoreCase: true },
    { type: 'literal', text: 'LONGTEXT', ignoreCase: true },
    { type: 'literal', text: 'ENUM', ignoreCase: true },
    { type: 'literal', text: 'boolean', ignoreCase: true },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'DECIMAL', ignoreCase: true },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'DECIMAL', ignoreCase: true },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'SIGNED', ignoreCase: true },
    { type: 'literal', text: 'UNSIGNED', ignoreCase: true },
    {
      type: 'class',
      parts: [ ' ', '\t', '\n', '\r' ],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'literal', text: 'CHAR', ignoreCase: true },
    { type: 'literal', text: 'VARCHAR', ignoreCase: true },
    { type: 'literal', text: 'CHAR', ignoreCase: true },
    { type: 'literal', text: 'VARCHAR', ignoreCase: true },
    { type: 'literal', text: 'NUMERIC', ignoreCase: true },
    { type: 'literal', text: 'DECIMAL', ignoreCase: true },
    { type: 'literal', text: 'INT', ignoreCase: true },
    { type: 'literal', text: 'INTEGER', ignoreCase: true },
    { type: 'literal', text: 'SMALLINT', ignoreCase: true },
    { type: 'literal', text: 'TINYINT', ignoreCase: true },
    { type: 'literal', text: 'BIGINT', ignoreCase: true },
    { type: 'literal', text: 'FLOAT', ignoreCase: true },
    { type: 'literal', text: 'DOUBLE', ignoreCase: true },
    { type: 'literal', text: 'BIT', ignoreCase: true },
    { type: 'literal', text: 'NUMERIC', ignoreCase: true },
    { type: 'literal', text: 'DECIMAL', ignoreCase: true },
    { type: 'literal', text: 'INT', ignoreCase: true },
    { type: 'literal', text: 'INTEGER', ignoreCase: true },
    { type: 'literal', text: 'SMALLINT', ignoreCase: true },
    { type: 'literal', text: 'TINYINT', ignoreCase: true },
    { type: 'literal', text: 'BIGINT', ignoreCase: true },
    { type: 'literal', text: 'FLOAT', ignoreCase: true },
    { type: 'literal', text: 'DOUBLE', ignoreCase: true },
    { type: 'literal', text: 'NUMERIC', ignoreCase: true },
    { type: 'literal', text: 'DECIMAL', ignoreCase: true },
    { type: 'literal', text: 'INT', ignoreCase: true },
    { type: 'literal', text: 'INTEGER', ignoreCase: true },
    { type: 'literal', text: 'SMALLINT', ignoreCase: true },
    { type: 'literal', text: 'TINYINT', ignoreCase: true },
    ... 168 more items
  ],
  found: 'B',
  location: {
    start: { offset: 17, line: 1, column: 18 },
    end: { offset: 18, line: 1, column: 19 }
  }
}
```

**Comment by planetbeing** [comment]
Sorry for filing all these issues. I can try to put together some pull requests for these issues. I am having a little bit of an issue building the library and running the tests since it appears that some of the dependencies specified in `package.json` that Dependabot made are too new.
