### ISSUE TITLE
[PostgreSQL] `WINDOW` support

### ISSUE THREAD

**Issue by goliatone** [taozhi8833998/node-sql-parser#816]
**Describe the bug**
Parser does not support `WINDOW` queries

**Database Engine**
- PostgreSQL.

**To Reproduce**

- SQL that be parsed:
```sql
SELECT id, trans_ref_no, amount, trans_date, entity_id
     , SUM(amount) OVER w AS trans_total
     , COUNT(*)    OVER w AS trans_count
FROM   transactiondb
WINDOW w AS (PARTITION BY entity_id, date_trunc('month', trans_date);
```
- node-sql-parser version: 3.9.4
- node version: v16.5.0

**Expected behavior**

Parser should be able to handle sql query with `WINDOW`

**Additional context**

Error output:

```
u [SyntaxError]: Expected "(", ",", "--", "/*", ";", "FROM", "GROUP", "HAVING", "LIMIT", "ORDER", "UNION", "WHERE", [ \t\n\r], or end of input but "w" found.
    at io (./node_modules/node-sql-parser/index.js:1:542242)
    at Object.parse [as postgresql] (./node_modules/node-sql-parser/index.js:1:672369)
    at r.value (./node_modules/node-sql-parser/index.js:1:1071580)
    at Object.<anonymous> (./sql-parse.js:36:12)
```

**Comment by taozhi8833998** [comment]
@goliatone try the `4.0.0` version
