### ISSUE TITLE
PostgreSQL typecast parsing error

### ISSUE THREAD

**Issue by kpmy** [taozhi8833998/node-sql-parser#868]
**Describe the bug**
When parsing query with ::int notation, parsing fails.

**Database Engine**
PostgreSQL

**To Reproduce**
error while inspecting query select * from data_file where (link->>'objectId')::varchar = '2719' or (link->>'objectIds')::jsonb @> '2719'
o [SyntaxError]: Expected "!=", "#-", "#>", "#>>", "%", "&&", "*", "+", ",", "-", "--", "/", "/*", ";", "<", "<=", "<>", "<@", "=", ">", ">=", "?", "?&", "?|", "@>", "AND", "BETWEEN", "GROUP", "HAVING", "ILIKE", "IN", "IS", "LIKE", "LIMIT", "NOT", "OR", "ORDER", "SIMILAR", "UNION", "||", [ \t\n\r], or end of input but ":" found.
    at peg$buildStructuredError (C:\Users\taozhi\learning\node-sql-parser\pegjs\postgresql.pegjs:3437:12)
    at Object.typeCase [as postgresql] (C:\Users\taozhi\learning\node-sql-parser\pegjs\postgresql.pegjs:27686:11)
    at r.parse (C:\Users\taozhi\learning\node-sql-parser\src\parser.js:20:43)
    at r.value (C:\Users\taozhi\learning\node-sql-parser\src\parser.js:7:26)
    at Query.submit (C:\dev\totr\asutb_passport_backend\main\db\index.js:34:28)
    at Client._pulseQueryQueue (C:\dev\totr\asutb_passport_backend\node_modules\pg\lib\client.js:481:45)
    at Client._handleReadyForQuery (C:\dev\totr\asutb_passport_backend\node_modules\pg\lib\client.js:292:10)
    at Connection.emit (node:events:390:28)
    at Connection.emit (node:domain:475:12)
    at C:\dev\totr\asutb_passport_backend\node_modules\pg\lib\connection.js:114:12
    at Parser.parse (C:\dev\totr\asutb_passport_backend\node_modules\pg-protocol\src\parser.ts:104:9)
    at Socket.<anonymous> (C:\dev\totr\asutb_passport_backend\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) 

node-sql-parser/build/postgresql@3.9.3
$ node -v
v16.10.0

**Expected behavior**
No exception.

**Comment by taozhi8833998** [comment]
@kpmy Upgrade the `node-sql-parser` module to `4.0.2` version could solve it. Here is the [code](https://runkit.com/taozhi8833998/5df6fe8f21d6b8001be36cb7)
