### ISSUE TITLE
failure on table name "window"

### ISSUE THREAD

**Issue by andrisi** [taozhi8833998/node-sql-parser#913]
**Describe the bug**
Calling astify('select * from window') fails, while "windows" works for example.

`u [SyntaxError]: Expected [A-Za-z0-9_] but end of input found.
    at vs (C:\Develop\spgjs\node_modules\node-sql-parser\index.js:1:302921)
    at Object.parse [as mysql] (C:\Develop\spgjs\node_modules\node-sql-parser\index.js:1:424106)
    at r.value (C:\Develop\spgjs\node_modules\node-sql-parser\index.js:1:1093902)
    at r.value (C:\Develop\spgjs\node_modules\node-sql-parser\index.js:1:1093582)
    at Server.onQuery (file:///C:/Develop/spgjs/server.js:60:31)
    at Connection.<anonymous> (file:///C:/Develop/spgjs/server.js:52:16)
    at Connection.emit (node:events:390:28)
    at ServerHandshake.dispatchCommands (C:\Develop\spgjs\node_modules\mysql2\lib\commands\server_handshake.js:96:22)
    at ServerHandshake.execute (C:\Develop\spgjs\node_modules\mysql2\lib\commands\command.js:45:22)
    at Connection.handlePacket (C:\Develop\spgjs\node_modules\mysql2\lib\connection.js:456:32) {
  expected: [
    {
      type: 'class',
      parts: [ [ 'A', 'Z' ], [ 'a', 'z' ], [ '0', '9' ], '_' ],
      inverted: false,
      ignoreCase: false
    },
    {
      type: 'class',
      parts: [ [ 'A', 'Z' ], [ 'a', 'z' ], [ '0', '9' ], '_' ],
      inverted: false,
      ignoreCase: false
    }
  ],
  found: null,
  location: {
    start: { offset: 20, line: 1, column: 21 },
    end: { offset: 20, line: 1, column: 21 }
  }
}`

**Database Engine**
MySQL

**To Reproduce**
SQL that be parsed: select * from window
node-sql-parser version: 4.0.8
node version: v16.13.1

**Comment by taozhi8833998** [comment]
@andrisi `window` is a [reserved word](https://dev.mysql.com/doc/mysqld-version-reference/en/keywords-8-0.html#keywords-8-0-detailed-W) in MySQL, which was added in 8.0.2. You can't use it as a table name.

**Comment by andrisi** [comment]
Ah, ok, understood. The code dump is an interesting side effect.

**Comment by taozhi8833998** [comment]
> Ah, ok, understood. The code dump is an interesting side effect.

en, I will try to make it more readable.
